## Content-Based Filtering

In [1]:
import pandas
movies = pandas.read_csv("movies.csv", sep=",")

In [2]:
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words="english")
movies["overview"] = movies["overview"].fillna("")

In [4]:
tfidf_matrix = tfidf.fit_transform(movies["overview"])

In [5]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 125840 stored elements and shape (4803, 20978)>

In [6]:
pandas.DataFrame(tfidf_matrix.toarray(), columns=tfidf.get_feature_names_out())

,00,000,007,07am,10,100,1000,101,108,10th,...,zuckerberg,zula,zuzu,zyklon,æon,éloigne,émigré,été,única,über
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4799,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4800,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4802,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
tfidf_matrix.shape

(4803, 20978)

In [8]:
movies["overview"]

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4798    El Mariachi just wants to play his guitar and ...
4799    A newlywed couple's honeymoon is upended by th...
4800    "Signed, Sealed, Delivered" introduces a dedic...
4801    When ambitious New York attorney Sam is sent t...
4802    Ever since the second grade when he first saw ...
Name: overview, Length: 4803, dtype: str

## Similarity matrix

In [9]:
from sklearn.metrics.pairwise import linear_kernel
similarity_matrix = linear_kernel(tfidf_matrix, tfidf_matrix)

In [10]:
similarity_matrix

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.02160533, 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.01488159, 0.        ,
        0.        ],
       ...,
       [0.        , 0.02160533, 0.01488159, ..., 1.        , 0.01609091,
        0.00701914],
       [0.        , 0.        , 0.        , ..., 0.01609091, 1.        ,
        0.01171696],
       [0.        , 0.        , 0.        , ..., 0.00701914, 0.01171696,
        1.        ]], shape=(4803, 4803))

In [11]:
similarity_matrix[0]

array([1., 0., 0., ..., 0., 0., 0.], shape=(4803,))

In [12]:
similarity_matrix[1]

array([0.        , 1.        , 0.        , ..., 0.02160533, 0.        ,
       0.        ], shape=(4803,))

## Find the most similar movies to a certain movie

In [13]:
movie_title = "John Carter"

In [14]:
idx = movies.loc[movies["title"]==movie_title].index[0]
idx

4

#### The key parameter tells sorted() to use the second element [1] of each (index, score) tuple
#### as the sorting criterion. The lambda function extracts the score value for comparison.
#### reverse=True orders from highest to lowest similarity

In [15]:
scores = list(enumerate(similarity_matrix[idx]))
scores

[(0, np.float64(0.0)),
 (1, np.float64(0.033368675996424305)),
 (2, np.float64(0.0)),
 (3, np.float64(0.010433403719159353)),
 (4, np.float64(1.0)),
 (5, np.float64(0.0)),
 (6, np.float64(0.009339192776152498)),
 (7, np.float64(0.037407042075763064)),
 (8, np.float64(0.0)),
 (9, np.float64(0.01714819056424443)),
 (10, np.float64(0.02015372184154536)),
 (11, np.float64(0.0)),
 (12, np.float64(0.03178129553727139)),
 (13, np.float64(0.0)),
 (14, np.float64(0.010712515993695904)),
 (15, np.float64(0.0)),
 (16, np.float64(0.045257098111540495)),
 (17, np.float64(0.020358841382635908)),
 (18, np.float64(0.016907757517459005)),
 (19, np.float64(0.016254574057966483)),
 (20, np.float64(0.00914487577692374)),
 (21, np.float64(0.01727519014981104)),
 (22, np.float64(0.0)),
 (23, np.float64(0.0)),
 (24, np.float64(0.01651050909357743)),
 (25, np.float64(0.0)),
 (26, np.float64(0.05387465159298631)),
 (27, np.float64(0.05231039324590807)),
 (28, np.float64(0.025467489988822038)),
 (29, np.float64(0.016102329289885736)),
 (30, np.float64(0.0)),
 (31, np.float64(0.01112130271029684)),
 (32, np.float64(0.021415531407536444)),
 (33, np.float64(0.0)),
 (34, np.float64(0.0)),
 (35, np.float64(0.015826523804524966)),
 (36, np.float64(0.0381036148024992)),
 (37, np.float64(0.0)),
 (38, np.float64(0.0)),
 (39, np.float64(0.02124047042069265)),
 (40, np.float64(0.00768676619264308)),
 (41, np.float64(0.01978947253021744)),
 (42, np.float64(0.0)),
 (43, np.float64(0.015863240253729538)),
 (44, np.float64(0.0)),
 (45, np.float64(0.022783108397171153)),
 (46, np.float64(0.08574401380341932)),
 (47, np.float64(0.05837115580794348)),
 (48, np.float64(0.027291542501988043)),
 (49, np.float64(0.006661619072989001)),
 (50, np.float64(0.05348134003905951)),
 (51, np.float64(0.020303156755951998)),
 (52, np.float64(0.0200156467845625)),
 (53, np.float64(0.009283858002248853)),
 (54, np.float64(0.055073031440828375)),
 (55, np.float64(0.0)),
 (56, np.float64(0.019705548314540633)),
 (57, np.float64(0.0)),
 (58, np.float64(0.054437289544783836)),
 (59, np.float64(0.014107530611723554)),
 (60, np.float64(0.0)),
 (61, np.float64(0.0)),
 (62, np.float64(0.0)),
 (63, np.float64(0.0)),
 (64, np.float64(0.023498148063470496)),
 (65, np.float64(0.009805867807909803)),
 (66, np.float64(0.0)),
 (67, np.float64(0.019190706170422227)),
 (68, np.float64(0.0)),
 (69, np.float64(0.0)),
 (70, np.float64(0.01094440728890874)),
 (71, np.float64(0.0069811676473432675)),
 (72, np.float64(0.0)),
 (73, np.float64(0.0)),
 (74, np.float64(0.0)),
 (75, np.float64(0.022943142552820633)),
 (76, np.float64(0.04563868300474624)),
 (77, np.float64(0.016138167839182024)),
 (78, np.float64(0.0)),
 (79, np.float64(0.025760454420038537)),
 (80, np.float64(0.0)),
 (81, np.float64(0.023055502664015293)),
 (82, np.float64(0.03199363546220082)),
 (83, np.float64(0.02830213467712009)),
 (84, np.float64(0.015367708891529573)),
 (85, np.float64(0.07927219338261442)),
 (86, np.float64(0.006837763027138118)),
 (87, np.float64(0.0)),
 (88, np.float64(0.0)),
 (89, np.float64(0.0)),
 (90, np.float64(0.0)),
 (91, np.float64(0.06511318345155809)),
 (92, np.float64(0.019392953319592822)),
 (93, np.float64(0.014362368494416106)),
 (94, np.float64(0.0)),
 (95, np.float64(0.0)),
 (96, np.float64(0.0)),
 (97, np.float64(0.018148157421771442)),
 (98, np.float64(0.026230631433396143)),
 (99, np.float64(0.0)),
 (100, np.float64(0.0)),
 (101, np.float64(0.008401329648238235)),
 (102, np.float64(0.008264600510095794)),
 (103, np.float64(0.0)),
 (104, np.float64(0.0)),
 (105, np.float64(0.0)),
 (106, np.float64(0.0)),
 (107, np.float64(0.04975088891450889)),
 (108, np.float64(0.043752278061972745)),
 (109, np.float64(0.00904550886236454)),
 (110, np.float64(0.0)),
 (111, np.float64(0.0)),
 (112, np.float64(0.008616077306773266)),
 (113, np.float64(0.0232436032763467)),
 (114, np.float64(0.0)),
 (115, np.float64(0.042964745097186265)),
 (116, np.float64(0.006845348430513409)),
 (117, np.float64(0.02383924013893402)),
 (118, np.float64(0.004307772202327974)),
 (119, np.float64(0.0)),
 (120, np.float64(0.02063396385983972)),
 (121, np.float64(0.0)),
 (122, np.float64(0.0)),
 (123, np.float64(0.01711828654912148)),
 (124, np.float64(0.0)),
 (125, np.float64(0.0052726074946179025)),
 (126, np.float64(0.0)),
 (127, np.float64(0.06404845195093838)),
 (128, np.float64(0.014785526097967284)),
 (129, np.float64(0.01637317351900404)),
 (130, np.float64(0.0)),
 (131, np.float64(0.013247495222260349)),
 (132, np.float64(0.016986814622034045)),
 (133, np.float64(0.009013912737246)),
 (134, np.float64(0.0)),
 (135, np.float64(0.0)),
 (136, np.float64(0.0)),
 (137, np.float64(0.007624305016523995)),
 (138, np.float64(0.0)),
 (139, np.float64(0.0)),
 (140, np.float64(0.014621772405641194)),
 (141, np.float64(0.0)),
 (142, np.float64(0.0)),
 (143, np.float64(0.006441374367745254)),
 (144, np.float64(0.0)),
 (145, np.float64(0.0)),
 (146, np.float64(0.011442209453330255)),
 (147, np.float64(0.0)),
 (148, np.float64(0.0)),
 (149, np.float64(0.0)),
 (150, np.float64(0.014514909084696942)),
 (151, np.float64(0.0)),
 (152, np.float64(0.0337894127869508)),
 (153, np.float64(0.0)),
 (154, np.float64(0.020238158756250162)),
 (155, np.float64(0.05465599273472926)),
 (156, np.float64(0.0)),
 (157, np.float64(0.0)),
 (158, np.float64(0.06136006069574056)),
 (159, np.float64(0.0)),
 (160, np.float64(0.0310376418629274)),
 (161, np.float64(0.0)),
 (162, np.float64(0.05810181561753072)),
 (163, np.float64(0.02455765274889435)),
 (164, np.float64(0.0)),
 (165, np.float64(0.0)),
 (166, np.float64(0.0)),
 (167, np.float64(0.0)),
 (168, np.float64(0.01866531692929332)),
 (169, np.float64(0.06572494101819237)),
 (170, np.float64(0.014262203354444069)),
 (171, np.float64(0.020213553025880373)),
 (172, np.float64(0.0)),
 (173, np.float64(0.006426217684023491)),
 (174, np.float64(0.04405940767569867)),
 (175, np.float64(0.0)),
 (176, np.float64(0.0)),
 (177, np.float64(0.0)),
 (178, np.float64(0.0)),
 (179, np.float64(0.00945629097392585)),
 (180, np.float64(0.0)),
 (181, np.float64(0.0)),
 (182, np.float64(0.00592115948559236)),
 (183, np.float64(0.0)),
 (184, np.float64(0.014890046218071499)),
 (185, np.float64(0.0)),
 (186, np.float64(0.0)),
 (187, np.float64(0.0)),
 (188, np.float64(0.0)),
 (189, np.float64(0.0)),
 (190, np.float64(0.021570096830354435)),
 (191, np.float64(0.0)),
 (192, np.float64(0.04264162048414869)),
 (193, np.float64(0.014649147138545352)),
 (194, np.float64(0.0)),
 (195, np.float64(0.02434986534338656)),
 (196, np.float64(0.0)),
 (197, np.float64(0.0)),
 (198, np.float64(0.0)),
 (199, np.float64(0.0)),
 (200, np.float64(0.04573250153848858)),
 (201, np.float64(0.0)),
 (202, np.float64(0.0)),
 (203, np.float64(0.0)),
 (204, np.float64(0.0)),
 (205, np.float64(0.0)),
 (206, np.float64(0.0)),
 (207, np.float64(0.03950100817441227)),
 (208, np.float64(0.0)),
 (209, np.float64(0.0)),
 (210, np.float64(0.0)),
 (211, np.float64(0.008053502358786161)),
 (212, np.float64(0.006514578034920521)),
 (213, np.float64(0.0)),
 (214, np.float64(0.0)),
 (215, np.float64(0.0)),
 (216, np.float64(0.0)),
 (217, np.float64(0.0)),
 (218, np.float64(0.0)),
 (219, np.float64(0.0)),
 (220, np.float64(0.0)),
 (221, np.float64(0.0)),
 (222, np.float64(0.017817525091440814)),
 (223, np.float64(0.02469657647746403)),
 (224, np.float64(0.012662616613306294)),
 (225, np.float64(0.014414400616726329)),
 (226, np.float64(0.0)),
 (227, np.float64(0.03220763022607363)),
 (228, np.float64(0.05095192690216123)),
 (229, np.float64(0.0)),
 (230, np.float64(0.02623367394148595)),
 (231, np.float64(0.014442290617753284)),
 (232, np.float64(0.0)),
 (233, np.float64(0.0)),
 (234, np.float64(0.015145778094171853)),
 (235, np.float64(0.0)),
 (236, np.float64(0.020263192301588857)),
 (237, np.float64(0.0)),
 (238, np.float64(0.0)),
 (239, np.float64(0.0)),
 (240, np.float64(0.0)),
 (241, np.float64(0.0067722890129990896)),
 (242, np.float64(0.0)),
 (243, np.float64(0.0)),
 (244, np.float64(0.0)),
 (245, np.float64(0.008711826055257733)),
 (246, np.float64(0.041717997266896484)),
 (247, np.float64(0.0)),
 (248, np.float64(0.014326342152548341)),
 (249, np.float64(0.0)),
 (250, np.float64(0.0)),
 (251, np.float64(0.0)),
 (252, np.float64(0.0)),
 (253, np.float64(0.02265922530400015)),
 (254, np.float64(0.006650792688227934)),
 (255, np.float64(0.012896368470763373)),
 (256, np.float64(0.026153918676188836)),
 (257, np.float64(0.030584604510354267)),
 (258, np.float64(0.003687806578639362)),
 (259, np.float64(0.0)),
 (260, np.float64(0.0)),
 (261, np.float64(0.020104879387202023)),
 (262, np.float64(0.03546421485928934)),
 (263, np.float64(0.0)),
 (264, np.float64(0.0)),
 (265, np.float64(0.0)),
 (266, np.float64(0.027922856347770603)),
 (267, np.float64(0.0)),
 (268, np.float64(0.0)),
 (269, np.float64(0.0)),
 (270, np.float64(0.05289174055081866)),
 (271, np.float64(0.01774986014471247)),
 (272, np.float64(0.0)),
 (273, np.float64(0.0)),
 (274, np.float64(0.0)),
 (275, np.float64(0.019012012076864985)),
 (276, np.float64(0.02210070952010449)),
 (277, np.float64(0.005171953174037606)),
 (278, np.float64(0.02620492372756335)),
 (279, np.float64(0.0320445184668943)),
 (280, np.float64(0.013066707226628685)),
 (281, np.float64(0.0)),
 (282, np.float64(0.0)),
 (283, np.float64(0.0)),
 (284, np.float64(0.0)),
 (285, np.float64(0.0)),
 (286, np.float64(0.02551952695772625)),
 (287, np.float64(0.0)),
 (288, np.float64(0.013393761102071822)),
 (289, np.float64(0.0)),
 (290, np.float64(0.0)),
 (291, np.float64(0.009622490529342706)),
 (292, np.float64(0.0)),
 (293, np.float64(0.0)),
 (294, np.float64(0.059721269746251145)),
 (295, np.float64(0.013850948453916684)),
 (296, np.float64(0.0069639065859347996)),
 (297, np.float64(0.00935590260380906)),
 (298, np.float64(0.008486495818406882)),
 (299, np.float64(0.0)),
 (300, np.float64(0.03179698829721199)),
 (301, np.float64(0.0)),
 (302, np.float64(0.0)),
 (303, np.float64(0.0)),
 (304, np.float64(0.03206725478560125)),
 (305, np.float64(0.03578394005663959)),
 (306, np.float64(0.007726185544930469)),
 (307, np.float64(0.0)),
 (308, np.float64(0.0)),
 (309, np.float64(0.0)),
 (310, np.float64(0.01399893758248774)),
 (311, np.float64(0.01324690348881613)),
 (312, np.float64(0.0)),
 (313, np.float64(0.032145106599792105)),
 (314, np.float64(0.0)),
 (315, np.float64(0.0)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0)),
 (318, np.float64(0.0)),
 (319, np.float64(0.0)),
 (320, np.float64(0.0)),
 (321, np.float64(0.0)),
 (322, np.float64(0.07826834318581481)),
 (323, np.float64(0.019866852649844356)),
 (324, np.float64(0.00603221501979096)),
 (325, np.float64(0.009715822571524412)),
 (326, np.float64(0.0)),
 (327, np.float64(0.0)),
 (328, np.float64(0.0)),
 (329, np.float64(0.0)),
 (330, np.float64(0.0)),
 (331, np.float64(0.02593549675040616)),
 (332, np.float64(0.0)),
 (333, np.float64(0.008838459012222235)),
 (334, np.float64(0.02363266602696133)),
 (335, np.float64(0.0)),
 (336, np.float64(0.00994266056124025)),
 (337, np.float64(0.025455855411282504)),
 (338, np.float64(0.0)),
 (339, np.float64(0.01745919496268492)),
 (340, np.float64(0.0)),
 (341, np.float64(0.020089065896757703)),
 (342, np.float64(0.0)),
 (343, np.float64(0.0)),
 (344, np.float64(0.02207015132799061)),
 (345, np.float64(0.09079218287485014)),
 (346, np.float64(0.0)),
 (347, np.float64(0.0)),
 (348, np.float64(0.0)),
 (349, np.float64(0.0)),
 (350, np.float64(0.0)),
 (351, np.float64(0.0)),
 (352, np.float64(0.023883601805589506)),
 (353, np.float64(0.0)),
 (354, np.float64(0.03257507459063306)),
 (355, np.float64(0.01398296085574484)),
 (356, np.float64(0.023825116200832504)),
 (357, np.float64(0.0)),
 (358, np.float64(0.008668311550706164)),
 (359, np.float64(0.0)),
 (360, np.float64(0.017953160345580043)),
 (361, np.float64(0.0)),
 (362, np.float64(0.03166834779008205)),
 (363, np.float64(0.006637103391835837)),
 (364, np.float64(0.0)),
 (365, np.float64(0.0)),
 (366, np.float64(0.0)),
 (367, np.float64(0.0)),
 (368, np.float64(0.0)),
 (369, np.float64(0.0)),
 (370, np.float64(0.0)),
 (371, np.float64(0.0)),
 (372, np.float64(0.0)),
 (373, np.float64(0.07112394697975578)),
 (374, np.float64(0.0)),
 (375, np.float64(0.0)),
 (376, np.float64(0.0)),
 (377, np.float64(0.0)),
 (378, np.float64(0.0)),
 (379, np.float64(0.0)),
 (380, np.float64(0.0)),
 (381, np.float64(0.0)),
 (382, np.float64(0.0)),
 (383, np.float64(0.0)),
 (384, np.float64(0.0)),
 (385, np.float64(0.011407564144343877)),
 (386, np.float64(0.0)),
 (387, np.float64(0.0)),
 (388, np.float64(0.0)),
 (389, np.float64(0.014382221127457503)),
 (390, np.float64(0.009518669504911264)),
 (391, np.float64(0.010338566571052935)),
 (392, np.float64(0.0)),
 (393, np.float64(0.0)),
 (394, np.float64(0.0)),
 (395, np.float64(0.023744536615487158)),
 (396, np.float64(0.0)),
 (397, np.float64(0.0)),
 (398, np.float64(0.0)),
 (399, np.float64(0.0)),
 (400, np.float64(0.021640428173372625)),
 (401, np.float64(0.04116784642875)),
 (402, np.float64(0.010848228649015888)),
 (403, np.float64(0.007522745564060013)),
 (404, np.float64(0.06030226569885217)),
 (405, np.float64(0.035806187126134044)),
 (406, np.float64(0.005450345122455705)),
 (407, np.float64(0.0)),
 (408, np.float64(0.00943408436948973)),
 (409, np.float64(0.00649252029116795)),
 (410, np.float64(0.02279218430814429)),
 (411, np.float64(0.0)),
 (412, np.float64(0.0200452665286035)),
 (413, np.float64(0.0)),
 (414, np.float64(0.0)),
 (415, np.float64(0.0)),
 (416, np.float64(0.0)),
 (417, np.float64(0.0)),
 (418, np.float64(0.016649932651121663)),
 (419, np.float64(0.03489914389791733)),
 (420, np.float64(0.03578786169047055)),
 (421, np.float64(0.0)),
 (422, np.float64(0.013534774420783956)),
 (423, np.float64(0.0)),
 (424, np.float64(0.034264287563403384)),
 (425, np.float64(0.0)),
 (426, np.float64(0.03584174579064028)),
 (427, np.float64(0.0)),
 (428, np.float64(0.008813953767297667)),
 (429, np.float64(0.0)),
 (430, np.float64(0.0)),
 (431, np.float64(0.0)),
 (432, np.float64(0.02480344523639407)),
 (433, np.float64(0.0)),
 (434, np.float64(0.0)),
 (435, np.float64(0.0)),
 (436, np.float64(0.0)),
 (437, np.float64(0.0)),
 (438, np.float64(0.0)),
 (439, np.float64(0.0406773490542124)),
 (440, np.float64(0.006149877872062611)),
 (441, np.float64(0.008310766329020813)),
 (442, np.float64(0.0)),
 (443, np.float64(0.048233119854634424)),
 (444, np.float64(0.01517739651407271)),
 (445, np.float64(0.0)),
 (446, np.float64(0.0)),
 (447, np.float64(0.012290686404449021)),
 (448, np.float64(0.020485159072648754)),
 (449, np.float64(0.0)),
 (450, np.float64(0.0)),
 (451, np.float64(0.0)),
 (452, np.float64(0.0)),
 (453, np.float64(0.0)),
 (454, np.float64(0.060610669974069796)),
 (455, np.float64(0.0)),
 (456, np.float64(0.015086950229015695)),
 (457, np.float64(0.0)),
 (458, np.float64(0.0)),
 (459, np.float64(0.0)),
 (460, np.float64(0.0)),
 (461, np.float64(0.018771137266414384)),
 (462, np.float64(0.03397453798799191)),
 (463, np.float64(0.0)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.0)),
 (467, np.float64(0.0)),
 (468, np.float64(0.0)),
 (469, np.float64(0.0)),
 (470, np.float64(0.0)),
 (471, np.float64(0.0)),
 (472, np.float64(0.0)),
 (473, np.float64(0.05849726730091015)),
 (474, np.float64(0.0)),
 (475, np.float64(0.0)),
 (476, np.float64(0.010325034050201427)),
 (477, np.float64(0.016722562376129055)),
 (478, np.float64(0.010020389555722492)),
 (479, np.float64(0.00453351923752785)),
 (480, np.float64(0.020786849919204986)),
 (481, np.float64(0.0)),
 (482, np.float64(0.0)),
 (483, np.float64(0.0)),
 (484, np.float64(0.0)),
 (485, np.float64(0.0)),
 (486, np.float64(0.009022689106186584)),
 (487, np.float64(0.06275480086880951)),
 (488, np.float64(0.0)),
 (489, np.float64(0.011058500719038945)),
 (490, np.float64(0.0)),
 (491, np.float64(0.017190690781164652)),
 (492, np.float64(0.0)),
 (493, np.float64(0.020962975284714833)),
 (494, np.float64(0.0)),
 (495, np.float64(0.0)),
 (496, np.float64(0.010490520313642827)),
 (497, np.float64(0.0)),
 (498, np.float64(0.009074127017110281)),
 (499, np.float64(0.0)),
 (500, np.float64(0.05508082020613065)),
 (501, np.float64(0.008240613504248777)),
 (502, np.float64(0.030129489467462123)),
 (503, np.float64(0.0)),
 (504, np.float64(0.0)),
 (505, np.float64(0.03328763225618516)),
 (506, np.float64(0.0)),
 (507, np.float64(0.014191435701753024)),
 (508, np.float64(0.012580275044897418)),
 (509, np.float64(0.028058077465183816)),
 (510, np.float64(0.008798340039474935)),
 (511, np.float64(0.0)),
 (512, np.float64(0.0)),
 (513, np.float64(0.0)),
 (514, np.float64(0.0)),
 (515, np.float64(0.02149129732384898)),
 (516, np.float64(0.0)),
 (517, np.float64(0.02081203284308163)),
 (518, np.float64(0.02649104953721125)),
 (519, np.float64(0.0)),
 (520, np.float64(0.0)),
 (521, np.float64(0.0)),
 (522, np.float64(0.0)),
 (523, np.float64(0.005653536898355653)),
 (524, np.float64(0.014820667329577507)),
 (525, np.float64(0.0)),
 (526, np.float64(0.0)),
 (527, np.float64(0.0)),
 (528, np.float64(0.0)),
 (529, np.float64(0.05952690460008955)),
 (530, np.float64(0.0)),
 (531, np.float64(0.02172628940821147)),
 (532, np.float64(0.011810503512878805)),
 (533, np.float64(0.0)),
 (534, np.float64(0.0)),
 (535, np.float64(0.0)),
 (536, np.float64(0.0)),
 (537, np.float64(0.03377902642044296)),
 (538, np.float64(0.0)),
 (539, np.float64(0.035721805161470915)),
 (540, np.float64(0.0)),
 (541, np.float64(0.03323299762497831)),
 (542, np.float64(0.008835340675404415)),
 (543, np.float64(0.005596517067855569)),
 (544, np.float64(0.020366453236280717)),
 (545, np.float64(0.01555725652136555)),
 (546, np.float64(0.009686662719229003)),
 (547, np.float64(0.0)),
 (548, np.float64(0.0)),
 (549, np.float64(0.0)),
 (550, np.float64(0.013101223367845674)),
 (551, np.float64(0.0)),
 (552, np.float64(0.01434179096939347)),
 (553, np.float64(0.0)),
 (554, np.float64(0.0)),
 (555, np.float64(0.01950518411413811)),
 (556, np.float64(0.0)),
 (557, np.float64(0.010049499818067659)),
 (558, np.float64(0.0)),
 (559, np.float64(0.0)),
 (560, np.float64(0.0)),
 (561, np.float64(0.0)),
 (562, np.float64(0.0)),
 (563, np.float64(0.02998913345697007)),
 (564, np.float64(0.024755682723938945)),
 (565, np.float64(0.0)),
 (566, np.float64(0.0)),
 (567, np.float64(0.0)),
 (568, np.float64(0.007779224761962552)),
 (569, np.float64(0.0)),
 (570, np.float64(0.0)),
 (571, np.float64(0.01566136138668507)),
 (572, np.float64(0.0)),
 (573, np.float64(0.031029998052109386)),
 (574, np.float64(0.0)),
 (575, np.float64(0.0)),
 (576, np.float64(0.008472125011248706)),
 (577, np.float64(0.0)),
 (578, np.float64(0.0)),
 (579, np.float64(0.022573111976213114)),
 (580, np.float64(0.0)),
 (581, np.float64(0.0900594125581888)),
 (582, np.float64(0.022836613628991007)),
 (583, np.float64(0.0)),
 (584, np.float64(0.0)),
 (585, np.float64(0.020808377614610907)),
 (586, np.float64(0.0060893260762652545)),
 (587, np.float64(0.022198518090422132)),
 (588, np.float64(0.02997208608157952)),
 (589, np.float64(0.0)),
 (590, np.float64(0.0)),
 (591, np.float64(0.00875961739639285)),
 (592, np.float64(0.04403661344701933)),
 (593, np.float64(0.0)),
 (594, np.float64(0.0)),
 (595, np.float64(0.03733671458175879)),
 (596, np.float64(0.012301153523295704)),
 (597, np.float64(0.0)),
 (598, np.float64(0.0)),
 (599, np.float64(0.005745275971666855)),
 (600, np.float64(0.0262104603548376)),
 (601, np.float64(0.0)),
 (602, np.float64(0.020774410692259423)),
 (603, np.float64(0.0)),
 (604, np.float64(0.0)),
 (605, np.float64(0.0)),
 (606, np.float64(0.021526892991432133)),
 (607, np.float64(0.04538169103402193)),
 (608, np.float64(0.0)),
 (609, np.float64(0.029938076466136387)),
 (610, np.float64(0.015169864172183698)),
 (611, np.float64(0.0)),
 (612, np.float64(0.01149717548959324)),
 (613, np.float64(0.0)),
 (614, np.float64(0.0)),
 (615, np.float64(0.0)),
 (616, np.float64(0.0)),
 (617, np.float64(0.0)),
 (618, np.float64(0.020077916279963443)),

In [16]:
sorted(scores, key=lambda x: x[1], reverse=True)

[(4, np.float64(1.0)),
 (1254, np.float64(0.20497253140891997)),
 (4161, np.float64(0.16370347641323713)),
 (2932, np.float64(0.12239400129620456)),
 (3349, np.float64(0.1188715104057236)),
 (1307, np.float64(0.11468689553107403)),
 (3068, np.float64(0.11237609168095009)),
 (345, np.float64(0.09079218287485014)),
 (581, np.float64(0.0900594125581888)),
 (2998, np.float64(0.08877535757173034)),
 (4274, np.float64(0.08576462030578072)),
 (46, np.float64(0.08574401380341932)),
 (1735, np.float64(0.08506583325352486)),
 (2755, np.float64(0.08374900580033416)),
 (2968, np.float64(0.08283973259290776)),
 (1057, np.float64(0.07986162067710445)),
 (85, np.float64(0.07927219338261442)),
 (322, np.float64(0.07826834318581481)),
 (1300, np.float64(0.0775741581048838)),
 (2300, np.float64(0.07715566889765219)),
 (2155, np.float64(0.07713065113739949)),
 (2417, np.float64(0.07556384384487905)),
 (694, np.float64(0.07473047732188678)),
 (2265, np.float64(0.0714410805050381)),
 (373, np.float64(0.07112394697975578)),
 (3155, np.float64(0.0677951781850077)),
 (2925, np.float64(0.06693206038119995)),
 (169, np.float64(0.06572494101819237)),
 (91, np.float64(0.06511318345155809)),
 (2944, np.float64(0.06471967857461398)),
 (870, np.float64(0.0645428835850544)),
 (3373, np.float64(0.06429775907599448)),
 (3764, np.float64(0.06417057137204367)),
 (127, np.float64(0.06404845195093838)),
 (3270, np.float64(0.06326978138321863)),
 (1791, np.float64(0.06326874758473128)),
 (1709, np.float64(0.0631310994088229)),
 (3948, np.float64(0.06309849115527627)),
 (487, np.float64(0.06275480086880951)),
 (3072, np.float64(0.0625429684549036)),
 (2966, np.float64(0.06244708472318927)),
 (2192, np.float64(0.06155506525140263)),
 (158, np.float64(0.06136006069574056)),
 (773, np.float64(0.061066711999447534)),
 (454, np.float64(0.060610669974069796)),
 (404, np.float64(0.06030226569885217)),
 (1891, np.float64(0.06001327386732981)),
 (1341, np.float64(0.059802355537906714)),
 (294, np.float64(0.059721269746251145)),
 (529, np.float64(0.05952690460008955)),
 (3133, np.float64(0.05937298619423642)),
 (4097, np.float64(0.05883192019217623)),
 (4224, np.float64(0.058695468702172605)),
 (473, np.float64(0.05849726730091015)),
 (47, np.float64(0.05837115580794348)),
 (162, np.float64(0.05810181561753072)),
 (2053, np.float64(0.058029950805801894)),
 (2909, np.float64(0.05799719956726909)),
 (1048, np.float64(0.0571700525263311)),
 (4385, np.float64(0.056993886886821686)),
 (4176, np.float64(0.056926597746629615)),
 (2341, np.float64(0.056191576277169884)),
 (1793, np.float64(0.05538023744600111)),
 (500, np.float64(0.05508082020613065)),
 (54, np.float64(0.055073031440828375)),
 (1564, np.float64(0.054738736739959486)),
 (155, np.float64(0.05465599273472926)),
 (2900, np.float64(0.054617797857307866)),
 (58, np.float64(0.054437289544783836)),
 (3914, np.float64(0.05435542991795837)),
 (724, np.float64(0.05432275346397926)),
 (26, np.float64(0.05387465159298631)),
 (4131, np.float64(0.05384776457560079)),
 (50, np.float64(0.05348134003905951)),
 (1319, np.float64(0.05333628005764863)),
 (755, np.float64(0.05331245188203113)),
 (1440, np.float64(0.05298053790994368)),
 (270, np.float64(0.05289174055081866)),
 (27, np.float64(0.05231039324590807)),
 (848, np.float64(0.05216553478536454)),
 (1917, np.float64(0.05200018993083395)),
 (2611, np.float64(0.05195326584810146)),
 (1974, np.float64(0.05187846387993067)),
 (4651, np.float64(0.051797295935223975)),
 (3568, np.float64(0.051590898570132195)),
 (228, np.float64(0.05095192690216123)),
 (748, np.float64(0.050199085344710764)),
 (1877, np.float64(0.04990601827546669)),
 (1201, np.float64(0.04977577145688119)),
 (107, np.float64(0.04975088891450889)),
 (2663, np.float64(0.049334353776528804)),
 (812, np.float64(0.04923633138181554)),
 (3105, np.float64(0.049204593789110025)),
 (1695, np.float64(0.0483365667331781)),
 (443, np.float64(0.048233119854634424)),
 (1079, np.float64(0.04783489410872848)),
 (2433, np.float64(0.04756871669119929)),
 (4653, np.float64(0.04752747290455587)),
 (653, np.float64(0.047388190098977115)),
 (977, np.float64(0.04724637165777989)),
 (1768, np.float64(0.0471230283849439)),
 (1599, np.float64(0.04703359413675343)),
 (1959, np.float64(0.04671520075103079)),
 (3899, np.float64(0.046623171934199376)),
 (2281, np.float64(0.04660595216685846)),
 (3953, np.float64(0.04601420885589026)),
 (200, np.float64(0.04573250153848858)),
 (76, np.float64(0.04563868300474624)),
 (3725, np.float64(0.0455618643619885)),
 (1559, np.float64(0.04544793418888482)),
 (1525, np.float64(0.04540951301853089)),
 (607, np.float64(0.04538169103402193)),
 (16, np.float64(0.045257098111540495)),
 (666, np.float64(0.045128950472429534)),
 (2587, np.float64(0.04499925826253404)),
 (2832, np.float64(0.0447941593962847)),
 (4062, np.float64(0.044733645888771066)),
 (671, np.float64(0.04455634054190102)),
 (2134, np.float64(0.04437455655485942)),
 (174, np.float64(0.04405940767569867)),
 (592, np.float64(0.04403661344701933)),
 (2492, np.float64(0.043928760300268294)),
 (108, np.float64(0.043752278061972745)),
 (1092, np.float64(0.043469955475036674)),
 (4197, np.float64(0.04342090677556618)),
 (4644, np.float64(0.04333490372784351)),
 (3339, np.float64(0.04325960268442425)),
 (115, np.float64(0.042964745097186265)),
 (3129, np.float64(0.042870605098225316)),
 (192, np.float64(0.04264162048414869)),
 (2444, np.float64(0.04257730012285965)),
 (3622, np.float64(0.042472919425905406)),
 (1694, np.float64(0.042440704845695176)),
 (2948, np.float64(0.042175725154491604)),
 (4681, np.float64(0.04196125572398302)),
 (1928, np.float64(0.04186378516255187)),
 (628, np.float64(0.041850939117896356)),
 (246, np.float64(0.041717997266896484)),
 (889, np.float64(0.041522991462621964)),
 (3865, np.float64(0.041513047748889545)),
 (401, np.float64(0.04116784642875)),
 (2724, np.float64(0.04102281338991135)),
 (439, np.float64(0.0406773490542124)),
 (805, np.float64(0.04025817493440431)),
 (3353, np.float64(0.04015325887291097)),
 (703, np.float64(0.04007191109937547)),
 (1492, np.float64(0.04006342220275068)),
 (4139, np.float64(0.039990253275671864)),
 (3143, np.float64(0.03989179229955795)),
 (4489, np.float64(0.03986326209129115)),
 (2936, np.float64(0.03974760358494528)),
 (893, np.float64(0.03972425656229799)),
 (2142, np.float64(0.039638896538980985)),
 (2010, np.float64(0.03959343184024481)),
 (207, np.float64(0.03950100817441227)),
 (690, np.float64(0.039460964255066094)),
 (4272, np.float64(0.039350710785087416)),
 (1643, np.float64(0.039310176487626844)),
 (3285, np.float64(0.03916154293878631)),
 (758, np.float64(0.03909923648947379)),
 (2895, np.float64(0.03896757706910759)),
 (1908, np.float64(0.03879896156579734)),
 (1976, np.float64(0.038699584326258134)),
 (2550, np.float64(0.03867148426997625)),
 (1633, np.float64(0.03843143581257178)),
 (4688, np.float64(0.03813653743157715)),
 (36, np.float64(0.0381036148024992)),
 (3338, np.float64(0.03806550450926273)),
 (2386, np.float64(0.03803564111607539)),
 (912, np.float64(0.037935123403707895)),
 (4193, np.float64(0.037750739540058115)),
 (4411, np.float64(0.037742561119524835)),
 (3554, np.float64(0.037712596408450615)),
 (1451, np.float64(0.037706338875390676)),
 (1600, np.float64(0.03770058733019667)),
 (2377, np.float64(0.037601861021694036)),
 (7, np.float64(0.037407042075763064)),
 (1510, np.float64(0.0373496466748079)),
 (595, np.float64(0.03733671458175879)),
 (3008, np.float64(0.037258138693100094)),
 (1731, np.float64(0.03714985680822667)),
 (3845, np.float64(0.0370273695078349)),
 (4246, np.float64(0.03677510102624857)),
 (3025, np.float64(0.03672096874590692)),
 (1678, np.float64(0.03667324261085046)),
 (3704, np.float64(0.03664731267884447)),
 (787, np.float64(0.03648106322521302)),
 (2431, np.float64(0.036370461262500306)),
 (939, np.float64(0.03629174162503717)),
 (3386, np.float64(0.03608113093783785)),
 (768, np.float64(0.0360519405119616)),
 (2229, np.float64(0.03604280041390838)),
 (1836, np.float64(0.03604267089107471)),
 (426, np.float64(0.03584174579064028)),
 (405, np.float64(0.035806187126134044)),
 (420, np.float64(0.03578786169047055)),
 (305, np.float64(0.03578394005663959)),
 (2787, np.float64(0.03574871190130733)),
 (539, np.float64(0.035721805161470915)),
 (262, np.float64(0.03546421485928934)),
 (2403, np.float64(0.035290947042410016)),
 (1236, np.float64(0.0351501979019305)),
 (2048, np.float64(0.035106458447118516)),
 (2114, np.float64(0.0350671132638325)),
 (4460, np.float64(0.03506424242281025)),
 (2320, np.float64(0.03494752831118314)),
 (419, np.float64(0.03489914389791733)),
 (2249, np.float64(0.034828291443593395)),
 (2213, np.float64(0.03478656149731014)),
 (1333, np.float64(0.03456945410857195)),
 (785, np.float64(0.03452992118049158)),
 (3668, np.float64(0.03452329760076973)),
 (696, np.float64(0.03446610085680914)),
 (3147, np.float64(0.03433978827223666)),
 (424, np.float64(0.034264287563403384)),
 (1533, np.float64(0.0342002013340818)),
 (657, np.float64(0.03408109415346418)),
 (462, np.float64(0.03397453798799191)),
 (4420, np.float64(0.03384606799204667)),
 (152, np.float64(0.0337894127869508)),
 (537, np.float64(0.03377902642044296)),
 (1, np.float64(0.033368675996424305)),
 (1985, np.float64(0.03336784948203336)),
 (4379, np.float64(0.033320312046241064)),
 (879, np.float64(0.03330772863213788)),
 (505, np.float64(0.03328763225618516)),
 (2539, np.float64(0.03327159918848045)),
 (541, np.float64(0.03323299762497831)),
 (764, np.float64(0.03310644136288942)),
 (1224, np.float64(0.03309094218319241)),
 (1962, np.float64(0.032931894519309834)),
 (4201, np.float64(0.032923924260091)),
 (2125, np.float64(0.032707376140110406)),
 (1610, np.float64(0.03268606337528683)),
 (1091, np.float64(0.03267547323872114)),
 (354, np.float64(0.03257507459063306)),
 (3642, np.float64(0.0325120379094178)),
 (1184, np.float64(0.03244830013015343)),
 (723, np.float64(0.03231409856528334)),
 (227, np.float64(0.03220763022607363)),
 (2203, np.float64(0.03217134317771609)),
 (2437, np.float64(0.032165218672551385)),
 (313, np.float64(0.032145106599792105)),
 (1494, np.float64(0.03210928755274694)),
 (304, np.float64(0.03206725478560125)),
 (2278, np.float64(0.03206388054917445)),
 (279, np.float64(0.0320445184668943)),
 (2678, np.float64(0.03202531604429863)),
 (82, np.float64(0.03199363546220082)),
 (1415, np.float64(0.03198212884543228)),
 (1438, np.float64(0.03191257132595482)),
 (3695, np.float64(0.031908973539310916)),
 (3576, np.float64(0.031827417097737044)),
 (300, np.float64(0.03179698829721199)),
 (12, np.float64(0.03178129553727139)),
 (362, np.float64(0.03166834779008205)),
 (1051, np.float64(0.031571929204875324)),
 (4332, np.float64(0.03156446419334397)),
 (3158, np.float64(0.03150270952786499)),
 (800, np.float64(0.03143566995424332)),
 (3776, np.float64(0.03141883792753234)),
 (3646, np.float64(0.03135255108920769)),
 (4530, np.float64(0.031143465014775964)),
 (1142, np.float64(0.031127149051489035)),
 (160, np.float64(0.0310376418629274)),
 (642, np.float64(0.031030717086205094)),
 (573, np.float64(0.031029998052109386)),
 (833, np.float64(0.031010763979535057)),
 (4267, np.float64(0.031003014305150588)),
 (2088, np.float64(0.030870108079864324)),
 (3293, np.float64(0.03083712752069809)),
 (838, np.float64(0.03075755017178601)),
 (4555, np.float64(0.030710576567737218)),
 (4392, np.float64(0.0306696139839318)),
 (2267, np.float64(0.03060432995788361)),
 (257, np.float64(0.030584604510354267)),
 (1902, np.float64(0.030482845282881737)),
 (2165, np.float64(0.030464359571964247)),
 (2654, np.float64(0.03038829372656394)),
 (2671, np.float64(0.0303736173459873)),
 (4685, np.float64(0.03035344836217966)),
 (1995, np.float64(0.030323724155664433)),
 (680, np.float64(0.030257326987591995)),
 (1274, np.float64(0.03015248647423744)),
 (502, np.float64(0.030129489467462123)),
 (920, np.float64(0.03011551626250773)),
 (1015, np.float64(0.03007466510802556)),
 (563, np.float64(0.02998913345697007)),
 (588, np.float64(0.02997208608157952)),
 (609, np.float64(0.029938076466136387)),
 (3514, np.float64(0.029873326260935435)),
 (2897, np.float64(0.029867573453070874)),
 (4213, np.float64(0.0297967691933396)),
 (1125, np.float64(0.029762060576342224)),
 (3221, np.float64(0.02973678959181201)),
 (4556, np.float64(0.029717447185886314)),
 (4614, np.float64(0.02971386251054935)),
 (1518, np.float64(0.02968809871445035)),
 (1198, np.float64(0.02966180460165607)),
 (1707, np.float64(0.029595321117804694)),
 (754, np.float64(0.02956255606779738)),
 (4009, np.float64(0.029447474541949254)),
 (3126, np.float64(0.029418774189192358)),
 (1632, np.float64(0.029360407818872364)),
 (823, np.float64(0.02936008317984165)),
 (3749, np.float64(0.029137313900988997)),
 (4291, np.float64(0.02906485934223304)),
 (1077, np.float64(0.02905492039335985)),
 (1822, np.float64(0.029035028011442227)),
 (2157, np.float64(0.02900527280827918)),
 (2247, np.float64(0.02887717724382434)),
 (898, np.float64(0.0287764337121634)),
 (1175, np.float64(0.028741642707975718)),
 (2757, np.float64(0.02861103965945106)),
 (4390, np.float64(0.028573243272485786)),
 (714, np.float64(0.028525503954055665)),
 (83, np.float64(0.02830213467712009)),
 (4465, np.float64(0.028288930309981763)),
 (3750, np.float64(0.02828307136803583)),
 (2410, np.float64(0.028271576409591326)),
 (2442, np.float64(0.028268462619529814)),
 (3287, np.float64(0.02823465284293046)),
 (2684, np.float64(0.028226878940228444)),
 (3184, np.float64(0.028088628289385537)),
 (509, np.float64(0.028058077465183816)),
 (2890, np.float64(0.028048320522711213)),
 (1649, np.float64(0.02796590989130375)),
 (3069, np.float64(0.027942544466747547)),
 (266, np.float64(0.027922856347770603)),
 (1523, np.float64(0.027915180903964876)),
 (1348, np.float64(0.027906412162462608)),
 (4362, np.float64(0.027894442328932963)),
 (849, np.float64(0.027836296338433136)),
 (692, np.float64(0.0277399999782318)),
 (3399, np.float64(0.027737305730203703)),
 (1534, np.float64(0.027713790001668057)),
 (3479, np.float64(0.027667486024086634)),
 (1106, np.float64(0.027661340343850663)),
 (813, np.float64(0.027614274612158898)),
 (4349, np.float64(0.027610349557349406)),
 (1395, np.float64(0.027524838437360366)),
 (4663, np.float64(0.02751423346853748)),
 (2233, np.float64(0.027302574947720353)),
 (4557, np.float64(0.02729295430015178)),
 (48, np.float64(0.027291542501988043)),
 (1433, np.float64(0.027236639452675487)),
 (3793, np.float64(0.027103777076180554)),
 (884, np.float64(0.027068743588114404)),
 (1818, np.float64(0.027061686250016734)),
 (2052, np.float64(0.02699851132467795)),
 (1268, np.float64(0.02694144452847516)),
 (4380, np.float64(0.02685142207127728)),
 (2960, np.float64(0.026817902699717972)),
 (2378, np.float64(0.026680914592515762)),
 (2860, np.float64(0.02661523107084833)),
 (778, np.float64(0.026578159901390928)),
 (2964, np.float64(0.0265684037812343)),
 (1776, np.float64(0.02656582397025788)),
 (3869, np.float64(0.026530619317515654)),
 (518, np.float64(0.02649104953721125)),
 (818, np.float64(0.02644154671107003)),
 (3710, np.float64(0.026440867889529318)),
 (2510, np.float64(0.0264299901148608)),
 (1351, np.float64(0.02632443858760074)),
 (2150, np.float64(0.026285383061369627)),
 (230, np.float64(0.02623367394148595)),
 (98, np.float64(0.026230631433396143)),
 (1864, np.float64(0.026215617538822174)),
 (600, np.float64(0.0262104603548376)),
 (278, np.float64(0.02620492372756335)),
 (1029, np.float64(0.026203041445868915)),
 (4469, np.float64(0.02615717532164036)),
 (1895, np.float64(0.02615418920457216)),
 (256, np.float64(0.026153918676188836)),
 (4270, np.float64(0.026113999446565398)),
 (2517, np.float64(0.026045848794973823)),
 (3563, np.float64(0.026018817493929824)),
 (2263, np.float64(0.026008881682010352)),
 (331, np.float64(0.02593549675040616)),
 (1129, np.float64(0.025772395170205888)),
 (79, np.float64(0.025760454420038537)),
 (1482, np.float64(0.02564423203662827)),
 (4158, np.float64(0.02562981818273318)),
 (4710, np.float64(0.02552347186866386)),
 (286, np.float64(0.02551952695772625)),
 (4497, np.float64(0.025496628673492207)),
 (28, np.float64(0.025467489988822038)),
 (337, np.float64(0.025455855411282504)),
 (1009, np.float64(0.025348760666488238)),
 (647, np.float64(0.025307754950264147)),
 (1286, np.float64(0.025248911983379394)),
 (1207, np.float64(0.02523495986469804)),
 (2584, np.float64(0.025187688334763182)),
 (2662, np.float64(0.025183096405544596)),
 (3910, np.float64(0.02517855696053911)),
 (3958, np.float64(0.02517534136808864)),
 (2317, np.float64(0.025167393894118303)),
 (4128, np.float64(0.02501510127102581)),
 (3500, np.float64(0.024964054736662262)),
 (2691, np.float64(0.024841437279285804)),
 (432, np.float64(0.02480344523639407)),
 (564, np.float64(0.024755682723938945)),
 (223, np.float64(0.02469657647746403)),
 (3533, np.float64(0.024635591922685225)),
 (163, np.float64(0.02455765274889435)),
 (2122, np.float64(0.02451128127786857)),
 (1094, np.float64(0.024470058325563426)),
 (2224, np.float64(0.024466732549407382)),
 (1460, np.float64(0.024440496082284113)),
 (195, np.float64(0.02434986534338656)),
 (4661, np.float64(0.024289542876440966)),
 (999, np.float64(0.024283904979669722)),
 (795, np.float64(0.02424770757432049)),
 (1127, np.float64(0.024236147246002027)),
 (3225, np.float64(0.02422007390120714)),
 (3024, np.float64(0.024170239238674836)),
 (3343, np.float64(0.024160631588327465)),
 (2541, np.float64(0.024147688481960358)),
 (2750, np.float64(0.02414160313587748)),
 (1031, np.float64(0.024108136786564382)),
 (1892, np.float64(0.024072491546034896)),
 (3522, np.float64(0.024025564058612454)),
 (2978, np.float64(0.024000521316715706)),
 (1956, np.float64(0.0239846975483696)),
 (1514, np.float64(0.023976364475564154)),
 (1217, np.float64(0.02396286089589341)),
 (1294, np.float64(0.023885642660560813)),
 (352, np.float64(0.023883601805589506)),
 (4185, np.float64(0.023863546697773352)),
 (117, np.float64(0.02383924013893402)),
 (356, np.float64(0.023825116200832504)),
 (2029, np.float64(0.02376592816641404)),
 (395, np.float64(0.023744536615487158)),
 (1852, np.float64(0.02374313047208959)),
 (840, np.float64(0.02371815458701695)),
 (334, np.float64(0.02363266602696133)),
 (1285, np.float64(0.023630634281154896)),
 (3611, np.float64(0.02359287542657044)),
 (2248, np.float64(0.023591269440598264)),
 (1018, np.float64(0.023504152871017335)),
 (64, np.float64(0.023498148063470496)),
 (4673, np.float64(0.0234701835284682)),
 (3062, np.float64(0.023460478604408513)),
 (2921, np.float64(0.023292748496044218)),
 (932, np.float64(0.023286023681692712)),
 (113, np.float64(0.0232436032763467)),
 (4571, np.float64(0.02317619170386227)),
 (1234, np.float64(0.023163828996115732)),
 (81, np.float64(0.023055502664015293)),
 (1145, np.float64(0.02304831695208413)),
 (2636, np.float64(0.02303796761810391)),
 (2784, np.float64(0.022970160845435503)),
 (75, np.float64(0.022943142552820633)),
 (1030, np.float64(0.02286350793687007)),
 (2429, np.float64(0.022852063042239787)),
 (582, np.float64(0.022836613628991007)),
 (410, np.float64(0.02279218430814429)),
 (45, np.float64(0.022783108397171153)),
 (2714, np.float64(0.022732905574071448)),
 (3423, np.float64(0.02272766156086044)),
 (903, np.float64(0.022706820212725454)),
 (253, np.float64(0.02265922530400015)),
 (2287, np.float64(0.022635848053270863)),
 (1765, np.float64(0.02262785824781107)),
 (2626, np.float64(0.0226119605722995)),
 (1455, np.float64(0.02258368148826068)),
 (579, np.float64(0.022573111976213114)),
 (2947, np.float64(0.022552560355074202)),
 (3771, np.float64(0.022512132131000458)),
 (3265, np.float64(0.022478677696754615)),
 (2753, np.float64(0.02247439416994333)),
 (4190, np.float64(0.02242681430959786)),
 (2598, np.float64(0.02241520937821302)),
 (1764, np.float64(0.022385625572120867)),
 (1303, np.float64(0.022378753019753544)),
 (1461, np.float64(0.022357201180532662)),
 (1330, np.float64(0.022295316933753872)),

#### Convert the NumPy array of similarity scores to a native Python list
#### The tolist() method transforms each np.float64 element into a standard float,
#### allowing sorted() to return clean numeric values without the NumPy type wrapper

In [17]:
sorted(similarity_matrix[5].tolist(), reverse=True)

[0.9999999999999998,
 0.28269377551691705,
 0.24647209184826266,
 0.23671046045214342,
 0.22284657494531743,
 0.21139629084201758,
 0.17166864148468533,
 0.10119023772910764,
 0.09698331013627293,
 0.09441228946181329,
 0.09420458163538704,
 0.09387869751025701,
 0.093179656021935,
 0.09294607512398585,
 0.08922096637425693,
 0.08822773156402856,
 0.08703321890643594,
 0.08655694622282886,
 0.07939905109264418,
 0.07824238152983498,
 0.0771307649186758,
 0.0770514400121716,
 0.07666361494130405,
 0.07553757363470058,
 0.07361132574539064,
 0.0730490466716229,
 0.07284646449723593,
 0.07255069266221406,
 0.07217331418966348,
 0.07214356973032558,
 0.06945848378728416,
 0.06936893001217233,
 0.06881212373296748,
 0.06876117376909216,
 0.06775861287012117,
 0.06714323008705704,
 0.06666577399021334,
 0.06635302952940192,
 0.06622358568674479,
 0.06578785204496,
 0.06511642814091788,
 0.064350600201051,
 0.06402613885361341,
 0.06371822899573716,
 0.06353750224737026,
 0.06242336147120036,
 0.06143843985787469,
 0.06139450275780043,
 0.0613506375377874,
 0.06087830005768986,
 0.06062862585903442,
 0.060627853074465714,
 0.060367683262824844,
 0.059511341035912976,
 0.05934156088768781,
 0.0583605123282354,
 0.0580417075017843,
 0.05790332379866165,
 0.057900106917374496,
 0.05780844385812319,
 0.057536058142551305,
 0.05749212624803003,
 0.057215379225483885,
 0.05710562250048796,
 0.056909226130246265,
 0.056586498373360106,
 0.05620908647053701,
 0.056196086640626634,
 0.055571779506253464,
 0.05543148783407088,
 0.05525942136258854,
 0.055017448890000584,
 0.055005220075627664,
 0.0546885453659819,
 0.05431129620674322,
 0.05426823485346395,
 0.054142641265544675,
 0.053957636480054645,
 0.053880911776438146,
 0.053871070547694654,
 0.05372327823933379,
 0.053660028715262195,
 0.05351496512853149,
 0.05340313566394415,
 0.05319286964576112,
 0.053139184805614824,
 0.052898388740354046,
 0.05264766260183854,
 0.05236999046865711,
 0.0522125071541926,
 0.05184912507036024,
 0.05179502375303796,
 0.05145277417007358,
 0.0511867173452672,
 0.0508000167902042,
 0.050488206724028505,
 0.05014665827850672,
 0.04993997331200512,
 0.04986071598067233,
 0.04984354636054641,
 0.049800840006960785,
 0.04975859362930841,
 0.049573967644340584,
 0.04929117820971462,
 0.04914442475552158,
 0.049139643579124904,
 0.04881957276221157,
 0.0486966555937848,
 0.04856458098353211,
 0.048363280786732125,
 0.04834497034052953,
 0.047970288178871084,
 0.047851741009668484,
 0.04747260558313948,
 0.0472745575198685,
 0.04724950519449549,
 0.04683649649383846,
 0.04683004743690721,
 0.04677336894672188,
 0.04673883950067899,
 0.046616649090220987,
 0.04645828624994969,
 0.04635083188230296,
 0.04608417415853404,
 0.046078536368501524,
 0.046004049176636065,
 0.04591188045269025,
 0.04583203218919919,
 0.045718006473384046,
 0.04555122937000921,
 0.04551435708332377,
 0.04548899336918324,
 0.04538937192690912,
 0.045362028499262054,
 0.045129510883518215,
 0.044999253076613656,
 0.04496871705875997,
 0.04484270913949836,
 0.04478741033431648,
 0.0444863493690836,
 0.04443665304919026,
 0.04372174239641947,
 0.043584273464978174,
 0.04341069268871836,
 0.04314186019619496,
 0.04312017353602627,
 0.04299422472690802,
 0.0429933358063697,
 0.04290075137753901,
 0.042435891218108424,
 0.04242330904788269,
 0.04237425420648835,
 0.04236615519629089,
 0.042337697215683534,
 0.04227649316803806,
 0.0422017473598963,
 0.04216301991032158,
 0.04213721939772973,
 0.04210304970189072,
 0.04205909913456424,
 0.04204486494927688,
 0.04194090835577841,
 0.041731485577055125,
 0.04163502760305954,
 0.041618837696600554,
 0.04149931023148979,
 0.04109781942976012,
 0.04105334646039386,
 0.04095547008626553,
 0.04066080492599557,
 0.04065929898747929,
 0.04044713578086238,
 0.04040293315060596,
 0.04039287184601331,
 0.040259982063171565,
 0.04023648381281196,
 0.04015992696225142,
 0.04015481946488395,
 0.040036639087620875,
 0.040030513924114684,
 0.03989063261549236,
 0.03986635991023447,
 0.03974106302755726,
 0.039624224748367194,
 0.0395928774516603,
 0.03951023999023719,
 0.039440395067174595,
 0.039356352570340584,
 0.03934553027026265,
 0.039233642748308074,
 0.03911923054969152,
 0.03911407477016902,
 0.03909966534150778,
 0.03902268931312534,
 0.03900201482361388,
 0.038970754285560405,
 0.03895180231258619,
 0.03878036913804795,
 0.03876920899726444,
 0.03858080372335546,
 0.038550633444656604,
 0.03852411205148137,
 0.03846721799698821,
 0.03841025551694074,
 0.038210428823612905,
 0.03793764703495162,
 0.037379534048069846,
 0.03703171413633901,
 0.036995916971636414,
 0.03692526911950605,
 0.03680264558126996,
 0.03674576277828756,
 0.036649031499860193,
 0.03662377552455423,
 0.03662345610752907,
 0.036542646130530945,
 0.03654169828862283,
 0.0364696635689629,
 0.036302284752574236,
 0.03627406823078279,
 0.03622336664426929,
 0.036089149696975194,
 0.03604305229753487,
 0.0359513926261133,
 0.03594141941587908,
 0.03589271664619167,
 0.035890532240936815,
 0.03571238807284436,
 0.0357119807986936,
 0.03562911314705352,
 0.035605948315549016,
 0.03549734685261582,
 0.03537256488322752,
 0.03529403475443952,
 0.03525926095408275,
 0.03522331307039649,
 0.03521528722593546,
 0.03508282458273108,
 0.03507342253802725,
 0.035059623219123925,
 0.03502012679185238,
 0.034946602889767774,
 0.034887446402258764,
 0.03486533211819185,
 0.03463666270929074,
 0.03460598074286402,
 0.034491869790926916,
 0.0344065342385829,
 0.034347966906783614,
 0.0343446214651893,
 0.034273154374197756,
 0.0342164279862088,
 0.034038152911866716,
 0.033735523080984306,
 0.033730510852900006,
 0.0336865759823717,
 0.03366874882969101,
 0.03365423703510108,
 0.03358671553796873,
 0.033347191250739226,
 0.033344566939367715,
 0.03322039043402651,
 0.03315099803756853,
 0.03314217609915369,
 0.032988568610726736,
 0.03292500477296542,
 0.03288290305809309,
 0.032859814201863256,
 0.03268008741016349,
 0.032620895869745536,
 0.032594778861322345,
 0.03258966731652439,
 0.032510331210709904,
 0.032500570435296174,
 0.032382733839963165,
 0.03225715163652203,
 0.032222792628755,
 0.032218919551626764,
 0.032215716591201676,
 0.03221145668005559,
 0.03200504895580668,
 0.03163841397890215,
 0.031631688106514656,
 0.03157115171299347,
 0.03148260218163135,
 0.03133622038384054,
 0.031332874646873024,
 0.03128601090888789,
 0.031152794888631565,
 0.030999763826376328,
 0.030928019172144033,
 0.03085666369661695,
 0.030787086019450773,
 0.030767224318467314,
 0.030721958677734303,
 0.030677401962212067,
 0.03059387320502418,
 0.030543266700611065,
 0.030485479046399554,
 0.030471090924549662,
 0.030352543844312897,
 0.030337146226121065,
 0.030231444647187973,
 0.030210323718961575,
 0.030197948328827766,
 0.030160170739488058,
 0.030141441529009345,
 0.030004486261576712,
 0.029999125615988047,
 0.02998397515006106,
 0.02997968854338446,
 0.029971599511303543,
 0.029906597424605195,
 0.029895108254061616,
 0.029858620977107456,
 0.029757832436669802,
 0.029731181095424608,
 0.029691234917924067,
 0.029502290448360953,
 0.029449174984099376,
 0.02944496495646316,
 0.029439648894462257,
 0.02942010520781982,
 0.029418283349923375,
 0.029391246038753423,
 0.029352749520949354,
 0.029259592228132503,
 0.02923232797261142,
 0.029218331722499123,
 0.029203129817795135,
 0.029196792787807607,
 0.029167518629637568,
 0.02909100649852178,
 0.029067425383808534,
 0.029058463494946923,
 0.02902067849120294,
 0.02901140642046382,
 0.028978212421009526,
 0.02896317893380686,
 0.028953680782990005,
 0.028869196161266937,
 0.02886717139529181,
 0.02884928621788115,
 0.028821177443239403,
 0.028785751027406395,
 0.02878277749862403,
 0.028770691805478855,
 0.028768371140010324,
 0.028765558526327506,
 0.02850946473092407,
 0.02844111157540107,
 0.02834649794355053,
 0.028346130119457424,
 0.028229528812330103,
 0.02808552629119611,
 0.02804975926755222,
 0.027985194406174863,
 0.0279396333018468,
 0.02793121853022257,
 0.027928566371138778,
 0.02790958041698038,
 0.02789706087336969,
 0.0278597278062321,
 0.027837030162105755,
 0.027830050253069883,
 0.02773104269281698,
 0.02763964326483348,
 0.02761652781764876,
 0.027549021704130094,
 0.027540176814181333,
 0.027534556433682654,
 0.027511153488460623,
 0.027500615447387262,
 0.02745486576457664,
 0.027412765098196235,
 0.02740839680824664,
 0.02740685468251596,
 0.027308094666694132,
 0.02727724606007234,
 0.027210124238630996,
 0.02720980158713401,
 0.027183754402600947,
 0.02716977311485928,
 0.027130298973004993,
 0.027072088536534013,
 0.027063055672594396,
 0.027037033351697815,
 0.027030877103293844,
 0.026927023051186504,
 0.02692007967591735,
 0.026869093618309168,
 0.026846610726097245,
 0.026841890025847377,
 0.02684072586762059,
 0.026816885486453324,
 0.026800619227185747,
 0.026800533435645094,
 0.02677533212841906,
 0.026770476861606208,
 0.02673478040397053,
 0.02672570769002217,
 0.026710061183869736,
 0.026644812684837278,
 0.026637331568850075,
 0.026547406007040586,
 0.02653600591821673,
 0.026501378478048437,
 0.02649504840422523,
 0.026483640275832727,
 0.026460722612949853,
 0.02643871176183646,
 0.026418635431053588,
 0.026404847051521112,
 0.026396628329929027,
 0.026388020240805086,
 0.026344577471972466,
 0.026322383135258535,
 0.026281830967171477,
 0.02624514982409359,
 0.026228945696192472,
 0.026206311057732714,
 0.02609610239182197,
 0.026091562915655796,
 0.026049610768229276,
 0.026040313514702432,
 0.026017530185113782,
 0.025995017556297736,
 0.02598927379530188,
 0.025978839075593722,
 0.025943741998280603,
 0.02593090948597778,
 0.02592151105552185,
 0.0259034720116594,
 0.02588741357614649,
 0.02581954224978158,
 0.025812000892888144,
 0.02578615630844367,
 0.025777448953522932,
 0.025771744332107806,
 0.025770806630194255,
 0.025675001433487308,
 0.0256411492898108,
 0.025570305031704058,
 0.0255622156629977,
 0.025549337612596694,
 0.025543319362257816,
 0.025541201060529144,
 0.02551880250911997,
 0.02550614474864141,
 0.02546651009297812,
 0.025433786409444874,
 0.025415664801312104,
 0.025398667414815248,
 0.02535734913661839,
 0.025343040235392387,
 0.025302474324048665,
 0.025276658550023885,
 0.025220779581437612,
 0.025196244805204583,
 0.024999340511685123,
 0.02498416579767805,
 0.024919245761221336,
 0.024888893233498764,
 0.024880862239143306,
 0.02487944023970075,
 0.02484934086332981,
 0.02484538583721135,
 0.02481169431019452,
 0.024734156630845223,
 0.024717143833231783,
 0.024716695846132498,
 0.024710088220558465,
 0.024707979696060763,
 0.024610757070570685,
 0.02458472773589431,
 0.02449574312989411,
 0.024482665257195,
 0.024414096162851322,
 0.024405290965926998,
 0.024325106957448182,
 0.02432298067938585,
 0.02420059128988064,
 0.024184469164779135,
 0.024146995346381275,
 0.024128246300024383,
 0.024111010333557566,
 0.024059766489714605,
 0.024057950157231958,
 0.024019919326693763,
 0.02398030415497548,
 0.023934979942879492,
 0.023931762770463445,
 0.023918513886895098,
 0.023880369102157083,
 0.02385874299560171,
 0.02384722261244705,
 0.023824562155418297,
 0.02378182039511489,
 0.02372842316467155,
 0.023723150238973322,
 0.023612626977652842,
 0.02360931342236969,
 0.02360123495670884,
 0.023571523553473524,
 0.023568850269739178,
 0.023551145808233833,
 0.023508539724878957,
 0.023506780674071217,
 0.023483691092410882,
 0.023474001829581145,
 0.02344903452950141,
 0.023400772499837214,
 0.023340959300094822,
 0.02333337840643704,
 0.023324639294601636,
 0.023258013105882366,
 0.02325343146880187,
 0.02319585711523727,
 0.02312575268382306,
 0.023063405009950584,
 0.023006884775008965,
 0.02296604437517618,
 0.022955207443016816,
 0.02289194417912233,
 0.022878835283284972,
 0.022838820417332466,
 0.02283764540874244,
 0.022824998036161552,
 0.022799905262782683,
 0.022788081200101114,
 0.02276595625706435,
 0.022661403514644365,
 0.022621377429132953,
 0.022558448340362088,
 0.02255504374850707,
 0.02254365957617114,
 0.02250265834846442,
 0.022493476970519014,
 0.022433011668201296,
 0.022419030576118246,
 0.022406045205834498,
 0.02240459357369429,
 0.02238232390455676,
 0.022381406636405837,
 0.02236013123133905,
 0.02234213160208701,
 0.022319381757278746,
 0.022252754554010677,
 0.022230360536877405,
 0.022218248368417987,
 0.022211816235942466,
 0.022203876014797598,
 0.022200974262543423,
 0.022188420676669082,
 0.022173087791740893,
 0.022076233809473003,
 0.02206167735139183,
 0.022004093018786374,
 0.02200343540071276,
 0.02197284969121575,
 0.021954260382064304,
 0.02191780456999657,
 0.021903697728480786,
 0.021897293216115173,
 0.02187759244313389,
 0.0218592527104706,
 0.02184195931852205,
 0.021838199472368914,
 0.021782476010545677,
 0.021771797036098967,
 0.021771299007779094,
 0.02173730389702416,
 0.021730520121638442,
 0.021679586267055986,
 0.021669334744560956,
 0.02165423978471943,
 0.021639433931451967,
 0.02163680074517422,
 0.02153650112403877,
 0.021493532360279136,
 0.021491837683016986,
 0.021452885130546447,
 0.021438704882908687,
 0.021418730968013423,
 0.021392235598410705,
 0.02133216351928817,
 0.021257569791343925,
 0.021248006973859177,
 0.021232147670182645,
 0.021229942739244317,
 0.021199511757887323,
 0.021168924901226988,
 0.021127810150437007,
 0.021125946411950723,
 0.02103806862756399,
 0.020970472395509327,
 0.020969295092771068,
 0.020916008761227275,
 0.020907935680331516,
 0.02088413040249511,
 0.020844419385104052,
 0.020810997983249535,
 0.02079153516781137,
 0.02078338628304796,
 0.0207790099807864,
 0.0207437370070835,
 0.020721317092520872,
 0.02072059347286116,
 0.020697079820341406,
 0.02069369617769526,
 0.02066280306974144,
 0.020637800330299123,
 0.020629597266073604,
 0.020614577811564633,
 0.020604750684637196,
 0.020596341053744728,
 0.020588048421586232,
 0.020563370052484615,
 0.020560614529823218,
 0.020534020412855576,
 0.020531594172216915,
 0.020503452137354137,
 0.020481429910649294,
 0.020461920303490706,
 0.020459209668557517,
 0.020453006894732402,
 0.020450713203056154,
 0.020443574103132293,
 0.020442679934053354,
 0.020439517779359102,
 0.020438430612134895,
 0.02041187761995052,
 0.020342150739317055,
 0.020332662191686175,
 0.020330941563740223,
 0.020317198774534324,
 0.02030745169168699,
 0.02026440487675534,
 0.020261822672395825,
 0.020261504011903835,
 0.020247108505808437,
 0.020235301762687168,
 0.020211641465827004,
 0.020196039937903122,
 0.02016768754469651,
 0.02016691891202161,
 0.02010842710765943,
 0.020076804270955664,
 0.02006975676622019,
 0.02006329981238214,
 0.020050722405971253,
 0.020021995023513917,
 0.020007959087673468,
 0.019989785816440692,
 0.019943508455941804,
 0.019905513624748086,
 0.019880831798917982,
 0.019872986596655064,
 0.019847626314107438,
 0.019843470687618346,
 0.019820141467493013,
 0.019811209829036676,
 0.01979775586709426,
 0.019779132297567843,
 0.019774563316716808,
 0.0197589429418321,
 0.019752010441322892,
 0.01974291805855344,
 0.019711800659801288,
 0.01969159921946275,
 0.019660169291648027,
 0.019656845141787956,
 0.019637278065216902,
 0.01962760968281585,
 0.019607990511864484,
 0.019574237090153077,
 0.019563416727298444,
 0.019559280406948765,
 0.01953443511933109,
 0.019529234080467417,
 0.019521372112654093,
 0.01950321364841567,
 0.019499603333295416,
 0.019497649311063108,
 0.01941674883317072,
 0.01934433304581623,
 0.019341903286820884,
 0.019321797983407548,
 0.01930605645166873,
 0.019299454004460016,
 0.01929327690206758,
 0.019288347963488314,
 0.019274645209379517,
 0.019219843907438985,
 0.019213253026938656,
 0.019187319113183773,
 0.019151248351200807,
 0.01911983555838438,
 0.019097215304903638,
 0.019053914320690552,
 0.019043414580008147,
 0.01901798774031989,
 0.018909913005787343,
 0.018898455037850505,
 0.018896575825097746,
 0.018894956989033127,
 0.018871356878351186,
 0.018869945940818575,
 0.018842047400316368,
 0.018840562246543596,
 0.018812528310162113,
 0.01877449842003224,
 0.01877100466288357,
 0.018766086225450555,
 0.01875002520625054,
 0.018742300272869748,
 0.01873964770811918,
 0.0187178194723152,
 0.018707032813162463,
 0.018690899195823816,
 0.01862227268143026,
 0.018614744805517027,
 0.018539611147813433,
 0.018538799074462944,
 0.0185193854152633,
 0.01851448023199798,
 0.018508598796752176,
 0.01847055999524782,
 0.018442384700302215,
 0.01842161570194496,
 0.018414923495066186,
 0.01840629883692872,
 0.01840345817824756,
 0.018386207736234495,
 0.01837091911652742,
 0.018368565422449135,
 0.018365345923224162,
 0.01834042227184478,
 0.018317978535230872,
 0.018306634918677976,
 0.018294188942036244,
 0.018289463428212926,
 0.0182774012243891,
 0.018245650320156757,
 0.018228145109913812,
 0.018214489025069357,
 0.018211804554642764,
 0.01820418423612874,
 0.018195909651818644,
 0.018175080480975544,
 0.01812515833281083,
 0.018118733316856834,
 0.01809033282311447,
 0.018078552584030197,
 0.018058489277630044,
 0.018038869125921474,
 0.017984436034895357,
 0.017980979164832902,
 0.017938289028864605,
 0.017883357442392337,
 0.017881607002968487,
 0.017879739408354932,
 0.017861720143515846,
 0.017857876214177858,
 0.01781323273723148,
 0.01781221743805108,
 0.017795519784193147,
 0.01779284871461964,
 0.017786343516581725,
 0.01777220815762309,
 0.017754449200864858,
 0.01775343299658125,
 0.017731342933027503,
 0.017726986599114192,
 0.017713707718964095,
 0.017703322829400337,
 0.017691690154042823,
 0.017678467465215085,
 0.017655172639570917,
 0.01764376706622259,
 0.0176206770000067,
 0.017613645008743645,
 0.017587778462551728,
 0.01758495901924692,
 0.01758161731828072,
 0.017550665944318034,
 0.017548531066931414,
 0.017536309845127794,
 0.01753456761314228,
 0.017520722405692427,
 0.017483252121129163,
 0.01746747545508049,
 0.017464479835532103,
 0.017463298864543498,
 0.017433391257152833,
 0.017372890184119714,
 0.017363321356288607,
 0.017349272436047378,
 0.017341711387102762,
 0.017312881416066815,
 0.017307956360466708,
 0.017280769848640465,
 0.017275033919118145,
 0.017258992593428613,
 0.017247806316495223,
 0.01724508436882637,
 0.017228456208624735,
 0.017191218616219587,
 0.017186119500294188,
 0.017182430720191204,
 0.017177010580523552,
 0.017176176188955943,
 0.01716891933179206,
 0.01716742865473562,
 0.017145917458267483,
 0.017138590414750958,
 0.01712600218908733,
 0.01712328328312977,
 0.01710629042756952,
 0.017102079595764864,
 0.017074369604491876,
 0.017070427150447664,
 0.017069557457550934,
 0.0170301795151957,
 0.017015328410918386,
 0.017004906128472958,
 0.017000870456127335,
 0.016886094915670388,
 0.01688460930156156,
 0.01688124998702199,
 0.016832644531820436,
 0.016822110465065404,
 0.016813174506408443,
 0.016794913646395487,
 0.016753949264472035,
 0.016746854189941804,
 0.01673646348274449,
 0.0167234350273335,
 0.016715757172452366,
 0.01667491256221302,
 0.01665659643866531,
 0.016643857048439875,
 0.01663975310226792,
 0.01662822028114591,
 0.016567560553984544,
 0.016555602607857874,
 0.016512861675531943,
 0.016478527524724444,
 0.016465022834268126,
 0.01645059337222921,
 0.016448619076930616,
 0.016436154735689434,
 0.01642991916356779,
 0.01642311921206161,
 0.016421204769053604,
 0.016411752261489786,
 0.016403744852462866,
 0.016375856127199395,
 0.016366891487713992,
 0.016365215112522348,
 0.01635570462366759,
 0.016334870699052855,
 0.016323394836193907,
 0.016302484716449617,
 0.01627592376005515,
 0.016253208435955648,
 0.016252523738339388,
 0.016236807406321458,
 0.016217237393840758,
 0.016188589713815735,
 0.016162065609669422,
 0.01615563182164444,
 0.016141593146082177,
 0.016130659571405196,
 0.016121008276242722,
 0.01608411131204804,
 0.016046871218717264,
 0.01603893120627305,
 0.01603061564536776,
 0.016021863389178458,
 0.016000152587736537,
 0.015994862879910015,
 0.015959602291228423,
 0.01595068045143593,
 0.015931016997441892,
 0.015913340868438035,
 0.01587601722305401,
 0.01587202315706658,
 0.015850622902989518,

In [18]:
scores

[(0, np.float64(0.0)),
 (1, np.float64(0.033368675996424305)),
 (2, np.float64(0.0)),
 (3, np.float64(0.010433403719159353)),
 (4, np.float64(1.0)),
 (5, np.float64(0.0)),
 (6, np.float64(0.009339192776152498)),
 (7, np.float64(0.037407042075763064)),
 (8, np.float64(0.0)),
 (9, np.float64(0.01714819056424443)),
 (10, np.float64(0.02015372184154536)),
 (11, np.float64(0.0)),
 (12, np.float64(0.03178129553727139)),
 (13, np.float64(0.0)),
 (14, np.float64(0.010712515993695904)),
 (15, np.float64(0.0)),
 (16, np.float64(0.045257098111540495)),
 (17, np.float64(0.020358841382635908)),
 (18, np.float64(0.016907757517459005)),
 (19, np.float64(0.016254574057966483)),
 (20, np.float64(0.00914487577692374)),
 (21, np.float64(0.01727519014981104)),
 (22, np.float64(0.0)),
 (23, np.float64(0.0)),
 (24, np.float64(0.01651050909357743)),
 (25, np.float64(0.0)),
 (26, np.float64(0.05387465159298631)),
 (27, np.float64(0.05231039324590807)),
 (28, np.float64(0.025467489988822038)),
 (29, np.float64(0.016102329289885736)),
 (30, np.float64(0.0)),
 (31, np.float64(0.01112130271029684)),
 (32, np.float64(0.021415531407536444)),
 (33, np.float64(0.0)),
 (34, np.float64(0.0)),
 (35, np.float64(0.015826523804524966)),
 (36, np.float64(0.0381036148024992)),
 (37, np.float64(0.0)),
 (38, np.float64(0.0)),
 (39, np.float64(0.02124047042069265)),
 (40, np.float64(0.00768676619264308)),
 (41, np.float64(0.01978947253021744)),
 (42, np.float64(0.0)),
 (43, np.float64(0.015863240253729538)),
 (44, np.float64(0.0)),
 (45, np.float64(0.022783108397171153)),
 (46, np.float64(0.08574401380341932)),
 (47, np.float64(0.05837115580794348)),
 (48, np.float64(0.027291542501988043)),
 (49, np.float64(0.006661619072989001)),
 (50, np.float64(0.05348134003905951)),
 (51, np.float64(0.020303156755951998)),
 (52, np.float64(0.0200156467845625)),
 (53, np.float64(0.009283858002248853)),
 (54, np.float64(0.055073031440828375)),
 (55, np.float64(0.0)),
 (56, np.float64(0.019705548314540633)),
 (57, np.float64(0.0)),
 (58, np.float64(0.054437289544783836)),
 (59, np.float64(0.014107530611723554)),
 (60, np.float64(0.0)),
 (61, np.float64(0.0)),
 (62, np.float64(0.0)),
 (63, np.float64(0.0)),
 (64, np.float64(0.023498148063470496)),
 (65, np.float64(0.009805867807909803)),
 (66, np.float64(0.0)),
 (67, np.float64(0.019190706170422227)),
 (68, np.float64(0.0)),
 (69, np.float64(0.0)),
 (70, np.float64(0.01094440728890874)),
 (71, np.float64(0.0069811676473432675)),
 (72, np.float64(0.0)),
 (73, np.float64(0.0)),
 (74, np.float64(0.0)),
 (75, np.float64(0.022943142552820633)),
 (76, np.float64(0.04563868300474624)),
 (77, np.float64(0.016138167839182024)),
 (78, np.float64(0.0)),
 (79, np.float64(0.025760454420038537)),
 (80, np.float64(0.0)),
 (81, np.float64(0.023055502664015293)),
 (82, np.float64(0.03199363546220082)),
 (83, np.float64(0.02830213467712009)),
 (84, np.float64(0.015367708891529573)),
 (85, np.float64(0.07927219338261442)),
 (86, np.float64(0.006837763027138118)),
 (87, np.float64(0.0)),
 (88, np.float64(0.0)),
 (89, np.float64(0.0)),
 (90, np.float64(0.0)),
 (91, np.float64(0.06511318345155809)),
 (92, np.float64(0.019392953319592822)),
 (93, np.float64(0.014362368494416106)),
 (94, np.float64(0.0)),
 (95, np.float64(0.0)),
 (96, np.float64(0.0)),
 (97, np.float64(0.018148157421771442)),
 (98, np.float64(0.026230631433396143)),
 (99, np.float64(0.0)),
 (100, np.float64(0.0)),
 (101, np.float64(0.008401329648238235)),
 (102, np.float64(0.008264600510095794)),
 (103, np.float64(0.0)),
 (104, np.float64(0.0)),
 (105, np.float64(0.0)),
 (106, np.float64(0.0)),
 (107, np.float64(0.04975088891450889)),
 (108, np.float64(0.043752278061972745)),
 (109, np.float64(0.00904550886236454)),
 (110, np.float64(0.0)),
 (111, np.float64(0.0)),
 (112, np.float64(0.008616077306773266)),
 (113, np.float64(0.0232436032763467)),
 (114, np.float64(0.0)),
 (115, np.float64(0.042964745097186265)),
 (116, np.float64(0.006845348430513409)),
 (117, np.float64(0.02383924013893402)),
 (118, np.float64(0.004307772202327974)),
 (119, np.float64(0.0)),
 (120, np.float64(0.02063396385983972)),
 (121, np.float64(0.0)),
 (122, np.float64(0.0)),
 (123, np.float64(0.01711828654912148)),
 (124, np.float64(0.0)),
 (125, np.float64(0.0052726074946179025)),
 (126, np.float64(0.0)),
 (127, np.float64(0.06404845195093838)),
 (128, np.float64(0.014785526097967284)),
 (129, np.float64(0.01637317351900404)),
 (130, np.float64(0.0)),
 (131, np.float64(0.013247495222260349)),
 (132, np.float64(0.016986814622034045)),
 (133, np.float64(0.009013912737246)),
 (134, np.float64(0.0)),
 (135, np.float64(0.0)),
 (136, np.float64(0.0)),
 (137, np.float64(0.007624305016523995)),
 (138, np.float64(0.0)),
 (139, np.float64(0.0)),
 (140, np.float64(0.014621772405641194)),
 (141, np.float64(0.0)),
 (142, np.float64(0.0)),
 (143, np.float64(0.006441374367745254)),
 (144, np.float64(0.0)),
 (145, np.float64(0.0)),
 (146, np.float64(0.011442209453330255)),
 (147, np.float64(0.0)),
 (148, np.float64(0.0)),
 (149, np.float64(0.0)),
 (150, np.float64(0.014514909084696942)),
 (151, np.float64(0.0)),
 (152, np.float64(0.0337894127869508)),
 (153, np.float64(0.0)),
 (154, np.float64(0.020238158756250162)),
 (155, np.float64(0.05465599273472926)),
 (156, np.float64(0.0)),
 (157, np.float64(0.0)),
 (158, np.float64(0.06136006069574056)),
 (159, np.float64(0.0)),
 (160, np.float64(0.0310376418629274)),
 (161, np.float64(0.0)),
 (162, np.float64(0.05810181561753072)),
 (163, np.float64(0.02455765274889435)),
 (164, np.float64(0.0)),
 (165, np.float64(0.0)),
 (166, np.float64(0.0)),
 (167, np.float64(0.0)),
 (168, np.float64(0.01866531692929332)),
 (169, np.float64(0.06572494101819237)),
 (170, np.float64(0.014262203354444069)),
 (171, np.float64(0.020213553025880373)),
 (172, np.float64(0.0)),
 (173, np.float64(0.006426217684023491)),
 (174, np.float64(0.04405940767569867)),
 (175, np.float64(0.0)),
 (176, np.float64(0.0)),
 (177, np.float64(0.0)),
 (178, np.float64(0.0)),
 (179, np.float64(0.00945629097392585)),
 (180, np.float64(0.0)),
 (181, np.float64(0.0)),
 (182, np.float64(0.00592115948559236)),
 (183, np.float64(0.0)),
 (184, np.float64(0.014890046218071499)),
 (185, np.float64(0.0)),
 (186, np.float64(0.0)),
 (187, np.float64(0.0)),
 (188, np.float64(0.0)),
 (189, np.float64(0.0)),
 (190, np.float64(0.021570096830354435)),
 (191, np.float64(0.0)),
 (192, np.float64(0.04264162048414869)),
 (193, np.float64(0.014649147138545352)),
 (194, np.float64(0.0)),
 (195, np.float64(0.02434986534338656)),
 (196, np.float64(0.0)),
 (197, np.float64(0.0)),
 (198, np.float64(0.0)),
 (199, np.float64(0.0)),
 (200, np.float64(0.04573250153848858)),
 (201, np.float64(0.0)),
 (202, np.float64(0.0)),
 (203, np.float64(0.0)),
 (204, np.float64(0.0)),
 (205, np.float64(0.0)),
 (206, np.float64(0.0)),
 (207, np.float64(0.03950100817441227)),
 (208, np.float64(0.0)),
 (209, np.float64(0.0)),
 (210, np.float64(0.0)),
 (211, np.float64(0.008053502358786161)),
 (212, np.float64(0.006514578034920521)),
 (213, np.float64(0.0)),
 (214, np.float64(0.0)),
 (215, np.float64(0.0)),
 (216, np.float64(0.0)),
 (217, np.float64(0.0)),
 (218, np.float64(0.0)),
 (219, np.float64(0.0)),
 (220, np.float64(0.0)),
 (221, np.float64(0.0)),
 (222, np.float64(0.017817525091440814)),
 (223, np.float64(0.02469657647746403)),
 (224, np.float64(0.012662616613306294)),
 (225, np.float64(0.014414400616726329)),
 (226, np.float64(0.0)),
 (227, np.float64(0.03220763022607363)),
 (228, np.float64(0.05095192690216123)),
 (229, np.float64(0.0)),
 (230, np.float64(0.02623367394148595)),
 (231, np.float64(0.014442290617753284)),
 (232, np.float64(0.0)),
 (233, np.float64(0.0)),
 (234, np.float64(0.015145778094171853)),
 (235, np.float64(0.0)),
 (236, np.float64(0.020263192301588857)),
 (237, np.float64(0.0)),
 (238, np.float64(0.0)),
 (239, np.float64(0.0)),
 (240, np.float64(0.0)),
 (241, np.float64(0.0067722890129990896)),
 (242, np.float64(0.0)),
 (243, np.float64(0.0)),
 (244, np.float64(0.0)),
 (245, np.float64(0.008711826055257733)),
 (246, np.float64(0.041717997266896484)),
 (247, np.float64(0.0)),
 (248, np.float64(0.014326342152548341)),
 (249, np.float64(0.0)),
 (250, np.float64(0.0)),
 (251, np.float64(0.0)),
 (252, np.float64(0.0)),
 (253, np.float64(0.02265922530400015)),
 (254, np.float64(0.006650792688227934)),
 (255, np.float64(0.012896368470763373)),
 (256, np.float64(0.026153918676188836)),
 (257, np.float64(0.030584604510354267)),
 (258, np.float64(0.003687806578639362)),
 (259, np.float64(0.0)),
 (260, np.float64(0.0)),
 (261, np.float64(0.020104879387202023)),
 (262, np.float64(0.03546421485928934)),
 (263, np.float64(0.0)),
 (264, np.float64(0.0)),
 (265, np.float64(0.0)),
 (266, np.float64(0.027922856347770603)),
 (267, np.float64(0.0)),
 (268, np.float64(0.0)),
 (269, np.float64(0.0)),
 (270, np.float64(0.05289174055081866)),
 (271, np.float64(0.01774986014471247)),
 (272, np.float64(0.0)),
 (273, np.float64(0.0)),
 (274, np.float64(0.0)),
 (275, np.float64(0.019012012076864985)),
 (276, np.float64(0.02210070952010449)),
 (277, np.float64(0.005171953174037606)),
 (278, np.float64(0.02620492372756335)),
 (279, np.float64(0.0320445184668943)),
 (280, np.float64(0.013066707226628685)),
 (281, np.float64(0.0)),
 (282, np.float64(0.0)),
 (283, np.float64(0.0)),
 (284, np.float64(0.0)),
 (285, np.float64(0.0)),
 (286, np.float64(0.02551952695772625)),
 (287, np.float64(0.0)),
 (288, np.float64(0.013393761102071822)),
 (289, np.float64(0.0)),
 (290, np.float64(0.0)),
 (291, np.float64(0.009622490529342706)),
 (292, np.float64(0.0)),
 (293, np.float64(0.0)),
 (294, np.float64(0.059721269746251145)),
 (295, np.float64(0.013850948453916684)),
 (296, np.float64(0.0069639065859347996)),
 (297, np.float64(0.00935590260380906)),
 (298, np.float64(0.008486495818406882)),
 (299, np.float64(0.0)),
 (300, np.float64(0.03179698829721199)),
 (301, np.float64(0.0)),
 (302, np.float64(0.0)),
 (303, np.float64(0.0)),
 (304, np.float64(0.03206725478560125)),
 (305, np.float64(0.03578394005663959)),
 (306, np.float64(0.007726185544930469)),
 (307, np.float64(0.0)),
 (308, np.float64(0.0)),
 (309, np.float64(0.0)),
 (310, np.float64(0.01399893758248774)),
 (311, np.float64(0.01324690348881613)),
 (312, np.float64(0.0)),
 (313, np.float64(0.032145106599792105)),
 (314, np.float64(0.0)),
 (315, np.float64(0.0)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0)),
 (318, np.float64(0.0)),
 (319, np.float64(0.0)),
 (320, np.float64(0.0)),
 (321, np.float64(0.0)),
 (322, np.float64(0.07826834318581481)),
 (323, np.float64(0.019866852649844356)),
 (324, np.float64(0.00603221501979096)),
 (325, np.float64(0.009715822571524412)),
 (326, np.float64(0.0)),
 (327, np.float64(0.0)),
 (328, np.float64(0.0)),
 (329, np.float64(0.0)),
 (330, np.float64(0.0)),
 (331, np.float64(0.02593549675040616)),
 (332, np.float64(0.0)),
 (333, np.float64(0.008838459012222235)),
 (334, np.float64(0.02363266602696133)),
 (335, np.float64(0.0)),
 (336, np.float64(0.00994266056124025)),
 (337, np.float64(0.025455855411282504)),
 (338, np.float64(0.0)),
 (339, np.float64(0.01745919496268492)),
 (340, np.float64(0.0)),
 (341, np.float64(0.020089065896757703)),
 (342, np.float64(0.0)),
 (343, np.float64(0.0)),
 (344, np.float64(0.02207015132799061)),
 (345, np.float64(0.09079218287485014)),
 (346, np.float64(0.0)),
 (347, np.float64(0.0)),
 (348, np.float64(0.0)),
 (349, np.float64(0.0)),
 (350, np.float64(0.0)),
 (351, np.float64(0.0)),
 (352, np.float64(0.023883601805589506)),
 (353, np.float64(0.0)),
 (354, np.float64(0.03257507459063306)),
 (355, np.float64(0.01398296085574484)),
 (356, np.float64(0.023825116200832504)),
 (357, np.float64(0.0)),
 (358, np.float64(0.008668311550706164)),
 (359, np.float64(0.0)),
 (360, np.float64(0.017953160345580043)),
 (361, np.float64(0.0)),
 (362, np.float64(0.03166834779008205)),
 (363, np.float64(0.006637103391835837)),
 (364, np.float64(0.0)),
 (365, np.float64(0.0)),
 (366, np.float64(0.0)),
 (367, np.float64(0.0)),
 (368, np.float64(0.0)),
 (369, np.float64(0.0)),
 (370, np.float64(0.0)),
 (371, np.float64(0.0)),
 (372, np.float64(0.0)),
 (373, np.float64(0.07112394697975578)),
 (374, np.float64(0.0)),
 (375, np.float64(0.0)),
 (376, np.float64(0.0)),
 (377, np.float64(0.0)),
 (378, np.float64(0.0)),
 (379, np.float64(0.0)),
 (380, np.float64(0.0)),
 (381, np.float64(0.0)),
 (382, np.float64(0.0)),
 (383, np.float64(0.0)),
 (384, np.float64(0.0)),
 (385, np.float64(0.011407564144343877)),
 (386, np.float64(0.0)),
 (387, np.float64(0.0)),
 (388, np.float64(0.0)),
 (389, np.float64(0.014382221127457503)),
 (390, np.float64(0.009518669504911264)),
 (391, np.float64(0.010338566571052935)),
 (392, np.float64(0.0)),
 (393, np.float64(0.0)),
 (394, np.float64(0.0)),
 (395, np.float64(0.023744536615487158)),
 (396, np.float64(0.0)),
 (397, np.float64(0.0)),
 (398, np.float64(0.0)),
 (399, np.float64(0.0)),
 (400, np.float64(0.021640428173372625)),
 (401, np.float64(0.04116784642875)),
 (402, np.float64(0.010848228649015888)),
 (403, np.float64(0.007522745564060013)),
 (404, np.float64(0.06030226569885217)),
 (405, np.float64(0.035806187126134044)),
 (406, np.float64(0.005450345122455705)),
 (407, np.float64(0.0)),
 (408, np.float64(0.00943408436948973)),
 (409, np.float64(0.00649252029116795)),
 (410, np.float64(0.02279218430814429)),
 (411, np.float64(0.0)),
 (412, np.float64(0.0200452665286035)),
 (413, np.float64(0.0)),
 (414, np.float64(0.0)),
 (415, np.float64(0.0)),
 (416, np.float64(0.0)),
 (417, np.float64(0.0)),
 (418, np.float64(0.016649932651121663)),
 (419, np.float64(0.03489914389791733)),
 (420, np.float64(0.03578786169047055)),
 (421, np.float64(0.0)),
 (422, np.float64(0.013534774420783956)),
 (423, np.float64(0.0)),
 (424, np.float64(0.034264287563403384)),
 (425, np.float64(0.0)),
 (426, np.float64(0.03584174579064028)),
 (427, np.float64(0.0)),
 (428, np.float64(0.008813953767297667)),
 (429, np.float64(0.0)),
 (430, np.float64(0.0)),
 (431, np.float64(0.0)),
 (432, np.float64(0.02480344523639407)),
 (433, np.float64(0.0)),
 (434, np.float64(0.0)),
 (435, np.float64(0.0)),
 (436, np.float64(0.0)),
 (437, np.float64(0.0)),
 (438, np.float64(0.0)),
 (439, np.float64(0.0406773490542124)),
 (440, np.float64(0.006149877872062611)),
 (441, np.float64(0.008310766329020813)),
 (442, np.float64(0.0)),
 (443, np.float64(0.048233119854634424)),
 (444, np.float64(0.01517739651407271)),
 (445, np.float64(0.0)),
 (446, np.float64(0.0)),
 (447, np.float64(0.012290686404449021)),
 (448, np.float64(0.020485159072648754)),
 (449, np.float64(0.0)),
 (450, np.float64(0.0)),
 (451, np.float64(0.0)),
 (452, np.float64(0.0)),
 (453, np.float64(0.0)),
 (454, np.float64(0.060610669974069796)),
 (455, np.float64(0.0)),
 (456, np.float64(0.015086950229015695)),
 (457, np.float64(0.0)),
 (458, np.float64(0.0)),
 (459, np.float64(0.0)),
 (460, np.float64(0.0)),
 (461, np.float64(0.018771137266414384)),
 (462, np.float64(0.03397453798799191)),
 (463, np.float64(0.0)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.0)),
 (467, np.float64(0.0)),
 (468, np.float64(0.0)),
 (469, np.float64(0.0)),
 (470, np.float64(0.0)),
 (471, np.float64(0.0)),
 (472, np.float64(0.0)),
 (473, np.float64(0.05849726730091015)),
 (474, np.float64(0.0)),
 (475, np.float64(0.0)),
 (476, np.float64(0.010325034050201427)),
 (477, np.float64(0.016722562376129055)),
 (478, np.float64(0.010020389555722492)),
 (479, np.float64(0.00453351923752785)),
 (480, np.float64(0.020786849919204986)),
 (481, np.float64(0.0)),
 (482, np.float64(0.0)),
 (483, np.float64(0.0)),
 (484, np.float64(0.0)),
 (485, np.float64(0.0)),
 (486, np.float64(0.009022689106186584)),
 (487, np.float64(0.06275480086880951)),
 (488, np.float64(0.0)),
 (489, np.float64(0.011058500719038945)),
 (490, np.float64(0.0)),
 (491, np.float64(0.017190690781164652)),
 (492, np.float64(0.0)),
 (493, np.float64(0.020962975284714833)),
 (494, np.float64(0.0)),
 (495, np.float64(0.0)),
 (496, np.float64(0.010490520313642827)),
 (497, np.float64(0.0)),
 (498, np.float64(0.009074127017110281)),
 (499, np.float64(0.0)),
 (500, np.float64(0.05508082020613065)),
 (501, np.float64(0.008240613504248777)),
 (502, np.float64(0.030129489467462123)),
 (503, np.float64(0.0)),
 (504, np.float64(0.0)),
 (505, np.float64(0.03328763225618516)),
 (506, np.float64(0.0)),
 (507, np.float64(0.014191435701753024)),
 (508, np.float64(0.012580275044897418)),
 (509, np.float64(0.028058077465183816)),
 (510, np.float64(0.008798340039474935)),
 (511, np.float64(0.0)),
 (512, np.float64(0.0)),
 (513, np.float64(0.0)),
 (514, np.float64(0.0)),
 (515, np.float64(0.02149129732384898)),
 (516, np.float64(0.0)),
 (517, np.float64(0.02081203284308163)),
 (518, np.float64(0.02649104953721125)),
 (519, np.float64(0.0)),
 (520, np.float64(0.0)),
 (521, np.float64(0.0)),
 (522, np.float64(0.0)),
 (523, np.float64(0.005653536898355653)),
 (524, np.float64(0.014820667329577507)),
 (525, np.float64(0.0)),
 (526, np.float64(0.0)),
 (527, np.float64(0.0)),
 (528, np.float64(0.0)),
 (529, np.float64(0.05952690460008955)),
 (530, np.float64(0.0)),
 (531, np.float64(0.02172628940821147)),
 (532, np.float64(0.011810503512878805)),
 (533, np.float64(0.0)),
 (534, np.float64(0.0)),
 (535, np.float64(0.0)),
 (536, np.float64(0.0)),
 (537, np.float64(0.03377902642044296)),
 (538, np.float64(0.0)),
 (539, np.float64(0.035721805161470915)),
 (540, np.float64(0.0)),
 (541, np.float64(0.03323299762497831)),
 (542, np.float64(0.008835340675404415)),
 (543, np.float64(0.005596517067855569)),
 (544, np.float64(0.020366453236280717)),
 (545, np.float64(0.01555725652136555)),
 (546, np.float64(0.009686662719229003)),
 (547, np.float64(0.0)),
 (548, np.float64(0.0)),
 (549, np.float64(0.0)),
 (550, np.float64(0.013101223367845674)),
 (551, np.float64(0.0)),
 (552, np.float64(0.01434179096939347)),
 (553, np.float64(0.0)),
 (554, np.float64(0.0)),
 (555, np.float64(0.01950518411413811)),
 (556, np.float64(0.0)),
 (557, np.float64(0.010049499818067659)),
 (558, np.float64(0.0)),
 (559, np.float64(0.0)),
 (560, np.float64(0.0)),
 (561, np.float64(0.0)),
 (562, np.float64(0.0)),
 (563, np.float64(0.02998913345697007)),
 (564, np.float64(0.024755682723938945)),
 (565, np.float64(0.0)),
 (566, np.float64(0.0)),
 (567, np.float64(0.0)),
 (568, np.float64(0.007779224761962552)),
 (569, np.float64(0.0)),
 (570, np.float64(0.0)),
 (571, np.float64(0.01566136138668507)),
 (572, np.float64(0.0)),
 (573, np.float64(0.031029998052109386)),
 (574, np.float64(0.0)),
 (575, np.float64(0.0)),
 (576, np.float64(0.008472125011248706)),
 (577, np.float64(0.0)),
 (578, np.float64(0.0)),
 (579, np.float64(0.022573111976213114)),
 (580, np.float64(0.0)),
 (581, np.float64(0.0900594125581888)),
 (582, np.float64(0.022836613628991007)),
 (583, np.float64(0.0)),
 (584, np.float64(0.0)),
 (585, np.float64(0.020808377614610907)),
 (586, np.float64(0.0060893260762652545)),
 (587, np.float64(0.022198518090422132)),
 (588, np.float64(0.02997208608157952)),
 (589, np.float64(0.0)),
 (590, np.float64(0.0)),
 (591, np.float64(0.00875961739639285)),
 (592, np.float64(0.04403661344701933)),
 (593, np.float64(0.0)),
 (594, np.float64(0.0)),
 (595, np.float64(0.03733671458175879)),
 (596, np.float64(0.012301153523295704)),
 (597, np.float64(0.0)),
 (598, np.float64(0.0)),
 (599, np.float64(0.005745275971666855)),
 (600, np.float64(0.0262104603548376)),
 (601, np.float64(0.0)),
 (602, np.float64(0.020774410692259423)),
 (603, np.float64(0.0)),
 (604, np.float64(0.0)),
 (605, np.float64(0.0)),
 (606, np.float64(0.021526892991432133)),
 (607, np.float64(0.04538169103402193)),
 (608, np.float64(0.0)),
 (609, np.float64(0.029938076466136387)),
 (610, np.float64(0.015169864172183698)),
 (611, np.float64(0.0)),
 (612, np.float64(0.01149717548959324)),
 (613, np.float64(0.0)),
 (614, np.float64(0.0)),
 (615, np.float64(0.0)),
 (616, np.float64(0.0)),
 (617, np.float64(0.0)),
 (618, np.float64(0.020077916279963443)),

In [19]:
movies_indices = [tpl[0] for tpl in scores[1:4]]
movies_indices

[1, 2, 3]

In [20]:
list(movies["title"].iloc[movies_indices])

["Pirates of the Caribbean: At World's End",
 'Spectre',
 'The Dark Knight Rises']

In [21]:
def similar_movies(movies_title, nr_movies):
    idx = movies.loc[movies["title"]==movies_title].index[0]
    scores = list(enumerate(similarity_matrix[idx]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)
    movies_indices = [tpl[0] for tpl in scores[1:nr_movies+1]]
    similar_titles = list(movies["title"].iloc[movies_indices])
    return similar_titles

In [22]:
similar_movies("Kung Fu Panda 3", 3)

['Kung Fu Panda 2',
 'My Big Fat Greek Wedding 2',
 'Once Upon a Time in the West']